-- ==========================================================================
-- 智问学伴：IT 行业主流技术知识库全量导入脚本 (V26)
-- 覆盖：Java、Spring微服务、MySQL、Redis、MQ中间件、前端Vue/React、云原生K8s/Docker、网络安全、数据结构算法、AI大模型、系统架构
-- 来源：对齐 CS-Notes、JavaGuide、各大厂开源权威技术图谱与高频面试题库
-- ==========================================================================
USE `tj_customer`;
SET NAMES utf8mb4;

-- 批量插入/更新 IT 行业专业技术知识库 (cs_knowledge: 122条核心技术条目)
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (101, 'Java 中 HashMap 的底层实现原理与扩容机制是怎样的？', 'HashMap 在 JDK 1.8 采用【数组 + 链表 + 红黑树】实现。默认初始容量为 16，负载因子为 0.75。通过 key 的 hashCode 计算二次扰动值确定数组槽位。当单链表节点数达到 8 且数组总长度达到 64 时，链表树化为红黑树以优化查询时间复杂度从 O(n) 至 O(log n)；节点数减少至 6 时退化为链表。当元素总数超过阈值（容量 × 0.75）时触发 2 倍扩容，扩容时通过高低位指针（e.hash & oldCap）重新映射位置，避免了 rehash。', 'HashMap,哈希表,底层原理,扩容机制,红黑树,链表,数组,负载因子,树化,哈希桶,Java集合', 'Java与后端开发', 1, 'it-101', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (102, 'ConcurrentHashMap 是如何保证线程安全的？JDK 7 与 JDK 8 有何区别？', 'JDK 1.7 中采用【分段锁 Segment】机制，继承自 ReentrantLock，并发度取决于 Segment 数组大小（默认16）。而在 JDK 1.8 中彻底摒弃了 Segment，改用【Node 数组 + CAS + synchronized】实现细粒度锁。仅在插入新节点时通过 CAS 保证原子性；哈希冲突时只锁住当前哈希桶的头节点（Node），大大减少了锁竞争。统计元素数量时使用 CounterCell 分散热点写入。', 'ConcurrentHashMap,线程安全,分段锁,Segment,CAS,synchronized,并发容器,哈希冲突', 'Java与后端开发', 1, 'it-102', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (103, 'Java 中基本数据类型与包装类型有什么区别？什么是自动装箱与拆箱？', 'Java 有 8 种基本类型（byte, short, int, long, float, double, char, boolean）。区别：1. 存储位置：基本类型局部变量存放在栈中，包装类型是对象存放在堆中；2. 默认值：基本类型有默认零值，包装类型默认为 null，适合在实体类和数据库映射中使用；3. 泛型支持：泛型只能使用包装类。自动装箱（如 int ➔ Integer）底层调用 `Integer.valueOf()`，自动拆箱（Integer ➔ int）调用 `intValue()`。Integer 内部维护了 -128 到 127 的常量缓存池。', '基本类型,包装类型,装箱,拆箱,自动装箱,自动拆箱,Integer缓存池,基本数据类型', 'Java与后端开发', 1, 'it-103', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (104, 'String、StringBuilder 与 StringBuffer 有什么区别？为什么 String 不可变？', '1. 不可变性：String 被 final 修饰且底层 byte 数组亦为 private final，不可被修改。不可变保证了哈希码缓存不变、字符串常量池复用、线程安全以及类加载与网络通信的安全性。2. 可变性与线程安全：StringBuilder 是可变字符序列，非线程安全，单线程字符拼接性能最高；StringBuffer 方法使用 synchronized 修饰，线程安全但有同步开销。频繁拼接字符串强烈推荐使用 StringBuilder。', 'String,StringBuilder,StringBuffer,不可变,字符串拼接,线程安全,常量池', 'Java与后端开发', 1, 'it-104', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (105, 'Java 反射机制的核心原理是什么？有哪些应用场景与性能开销？', '反射允许程序在运行时动态获取任意类的完整结构（类名、修饰符、字段、方法、注解）并动态调用方法或修改私有成员。核心类包括 Class、Method、Field、Constructor。底层通过 JVM native 方法或动态生成字节码调用。广泛应用于 Spring IoC 容器依赖注入、MyBatis ORM 映射、RPC 序列化框架及动态代理。反射会绕过编译器优化并产生额外类型安全校验，高频场景应适当做 Method 缓存或采用 MethodHandle/ReflectASM 优化。', '反射,反射机制,Class,Method,动态调用,性能开销,私有属性,获取类信息', 'Java与后端开发', 1, 'it-105', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (106, 'Java 异常体系结构是怎样的？Checked 异常与 Runtime 异常有什么区别？', '所有异常根类为 `Throwable`，分为两大子类：`Error`（严重硬件/JVM错误，如 OOM、StackOverflow，程序不应捕获）与 `Exception`（程序自身可处理的异常）。Exception 又分为：1. Checked 异常（受检异常，如 IOException, SQLException），编译器强制要求 try-catch 或 throws 显式处理；2. Unchecked 异常（非受检运行时异常，继承自 `RuntimeException`，如 NullPointerException, IndexOutOfBoundsException），通常由逻辑缺陷引起，编译器不强制处理。', '异常,异常体系,Throwable,Exception,Error,受检异常,运行时异常,RuntimeException,OOM', 'Java与后端开发', 1, 'it-106', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (107, 'Java 线程池的核心参数有哪些？完整工作流程与拒绝策略是怎样的？', 'ThreadPoolExecutor 包含 7 大核心参数：corePoolSize（核心线程数）、maximumPoolSize（最大线程数）、keepAliveTime（非核心空闲存活时间）、unit（时间单位）、workQueue（任务阻塞队列）、threadFactory（线程工厂）、handler（拒绝策略）。工作流程：新任务到来 ➔ 核心线程未满则创建核心线程 ➔ 核心线程已满则入队 ➔ 队列已满则创建非核心线程至最大数 ➔ 达到最大线程数且队列仍满则触发拒绝策略（AbortPolicy 抛异常、CallerRunsPolicy 调用者线程执行、DiscardPolicy 丢弃、DiscardOldestPolicy 丢弃队列最老任务）。', '线程池,核心参数,阻塞队列,拒绝策略,工作流程,ThreadPoolExecutor,线程数', 'Java与后端开发', 1, 'it-107', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (108, 'ThreadLocal 底层原理是什么？为什么会发生内存泄漏？如何正确避免？', 'ThreadLocal 用于线程间数据隔离。每个 Thread 内部维护一个 `ThreadLocalMap`，其 Entry 的 Key 为 ThreadLocal 的弱引用（WeakReference），Value 为真实变量的强引用。若外层 ThreadLocal 强引用断开，Key 会被 GC 回收变为 null，但 Value 是强引用且线程长期存活（如在线程池中），导致 Value 无法被回收产生内存泄漏。正确使用：使用完毕后必须在 `finally` 代码块中显式调用 `threadLocal.remove()` 清理。', 'ThreadLocal,内存泄漏,ThreadLocalMap,弱引用,线程隔离,remove方法', 'Java与后端开发', 1, 'it-108', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (109, 'JVM 运行时数据区是如何划分的？堆与栈的作用和区别是什么？', 'JVM 内存分为 5 大区域：1. 程序计数器（记录线程执行字节码指令行号，私有）；2. 虚拟机栈（存储局部变量表、操作数栈、动态链接、方法出口，私有）；3. 本地方法栈（为 Native 方法服务，私有）；4. 堆（Heap，存放所有对象实例与数组，垃圾回收主战场，共享）；5. 方法区/元空间（MetaSpace，存储类元信息、常量、静态变量，共享，JDK8移至本地内存）。堆是解决数据存储问题，栈是解决程序运行逻辑问题。', 'JVM,运行时数据区,堆,栈,方法区,程序计数器,元空间,内存划分,MetaSpace', 'Java与后端开发', 1, 'it-109', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (110, 'JVM 垃圾回收算法有哪些？G1 与 ZGC 收集器有什么核心特点？', '基础回收算法包括：标记-清除（易产生碎片）、标记-复制（无碎片但浪费一半空间，用于年轻代）、标记-整理（无碎片用于老年代）。G1 收集器将堆划分为等大小的独立 Region（Region 动态扮演 Eden/Survivor/Old/Humongous），采用增量并发标记和复制算法，允许用户设定目标最大停顿时间（MaxGCPauseMillis）并优先回收价值最大的 Region。ZGC 则是低延迟垃圾回收器，基于着色指针（Colored Pointer）与读屏障（Load Barrier）实现并发标记与并发整理，STW 停顿控制在毫秒级以内。', '垃圾回收,垃圾回收GC,G1,ZGC,标记清除,标记复制,标记整理,STW,Region,着色指针', 'Java与后端开发', 1, 'it-110', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (111, 'Java 中对象的强引用、软引用、弱引用与虚引用有什么区别？', '1. 强引用（StrongReference）：最常见的普通引用，只要强引用还在，垃圾回收器绝不会回收该对象，内存不足报 OOM；2. 软引用（SoftReference）：内存充足时不回收，系统内存即将溢出前进行二次回收，常用于实现内存敏感的高速缓存；3. 弱引用（WeakReference）：无论内存是否充足，只要触发垃圾回收必定被清理，典型应用为 ThreadLocalMap 与 WeakHashMap；4. 虚引用（PhantomReference）：形同虚设，必须配合引用队列（ReferenceQueue）使用，仅用于跟踪对象被回收的状态与资源清理。', '强引用,软引用,弱引用,虚引用,Reference,引用类型,引用队列,垃圾回收', 'Java与后端开发', 1, 'it-111', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (112, 'Java 8 Stream API 的核心概念与常用操作有哪些？使用上有何陷阱？', 'Stream 是对集合进行函数式高阶计算的抽象流水线。操作分为：中间操作（无状态 filter/map，有状态 distinct/sorted/limit，具备惰性求值特性）与终端操作（forEach/collect/reduce/count，触发真正计算）。避坑指南：1. Stream 只能消费一次，重复消费报 IllegalStateException；2. parallelStream 并行流默认使用全局 ForkJoinPool.commonPool，涉及 I/O 密集型任务会造成全局线程阻塞；3. 避免在 Stream 中修改外部共享变量产生竞态条件。', 'Stream,流式计算,Lambda,中间操作,终端操作,惰性求值,parallelStream,函数式编程', 'Java与后端开发', 1, 'it-112', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (113, 'Spring 框架中 IoC（控制反转）和 DI（依赖注入）的核心思想是什么？', 'IoC（Inversion of Control，控制反转）是一种将对象的创建、组装和生命周期管理从业务代码剥离交由容器（BeanFactory / ApplicationContext）统一托管的软件设计思想。DI（Dependency Injection，依赖注入）是 IoC 的具体实现手段，容器在运行时根据配置（注解如 @Autowired, @Resource）将依赖组件自动注入到目标对象中。优势在于：降低类与类之间的直接耦合，极大提升模块可测试性（方便 Mock 单元测试）与扩展性。', 'IoC,控制反转,依赖注入,依赖注入DI,Spring核心,BeanFactory,解耦', 'Spring与微服务', 1, 'it-113', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (114, 'Spring Bean 的生命周期是怎样的？从实例化到销毁经历了哪些阶段？', 'Spring Bean 完整生命周期包括：1. 实例化（Instantiation）：反射创建对象；2. 属性填充（Populate）：依赖注入赋值；3. Aware 接口回调（BeanNameAware, BeanFactoryAware, ApplicationContextAware）；4. 初始化前处理（BeanPostProcessor.postProcessBeforeInitialization）；5. 初始化（@PostConstruct ➔ InitializingBean.afterPropertiesSet ➔ 自定义 init-method）；6. 初始化后处理（BeanPostProcessor.postProcessAfterInitialization，AOP 代理对象在此生成）；7. 投入使用；8. 销毁（@PreDestroy ➔ DisposableBean.destroy ➔ destroy-method）。', 'Spring,Bean,生命周期,生命周期流程,Bean生命周期,实例化,初始化,销毁,BeanPostProcessor', 'Spring与微服务', 1, 'it-114', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (115, 'Spring 中的 Bean 是线程安全的吗？默认的作用域有哪些？', 'Spring 单例 Bean（Singleton）本身并不提供任何线程安全保证。如果 Bean 是无状态的（如标准的 Service、Dao、Controller，只包含逻辑不维护实例变量），则是线程安全的；如果 Bean 包含有状态的可变实例字段，多线程并发修改会产生线程安全问题。解决方案：1. 改用局部变量；2. 结合 ThreadLocal 保存线程私有变量；3. 声明为原型作用域 `@Scope("prototype")`。Spring 支持 5 种作用域：singleton、prototype，以及 Web 环境下的 request、session、application。', 'Spring,Bean,线程安全,作用域,单例,Singleton,Prototype,有状态Bean,无状态', 'Spring与微服务', 1, 'it-115', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (116, 'Spring AOP 的底层实现原理是什么？JDK 动态代理与 CGLIB 有何区别？', 'Spring AOP 基于动态代理机制，在运行时为目标类生成代理对象并在切点处织入增强逻辑。两种实现机制：1. JDK 动态代理：基于反射与 `InvocationHandler`，要求目标类必须实现至少一个接口，生成的代理类继承自 `Proxy`；2. CGLIB 代理：基于 ASM 字节码生成框架，通过动态生成目标类的子类覆盖非 final 方法进行拦截增强。Spring Boot 2.x/3.x 默认全面启用 CGLIB 代理（`proxyTargetClass=true`），以统一对接口和普通类的代理行为。', 'AOP,切面编程,动态代理,JDK动态代理,CGLIB,InvocationHandler,字节码增强', 'Spring与微服务', 1, 'it-116', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (117, 'Spring 事务传播行为有哪些？哪些常见场景会导致 @Transactional 事务失效？', 'Spring 支持 7 种传播行为，最常用的是 `REQUIRED`（支持当前事务，没有则新建）与 `REQUIRES_NEW`（挂起当前事务并开启独立新事务）。常见失效场景：1. 同类中非事务方法通过 `this.xxx()` 自调用事务方法（绕过了代理对象）；2. 方法修饰符非 `public`；3. 异常被内部 `try-catch` 吞掉未向外抛出；4. 抛出的异常与 `rollbackFor` 不匹配（默认只回滚 RuntimeException 和 Error，检查异常需指定 `rollbackFor=Exception.class`）；5. 数据库存储引擎不支持事务（如 MyISAM）；6. 异步多线程执行业务导致事务连接解绑。', 'Spring,事务,Spring事务,事务失效,失效场景,Transactional,事务传播,自调用', 'Spring与微服务', 1, 'it-117', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (118, 'Spring Boot 自动装配原理是什么？@EnableAutoConfiguration 是如何工作的？', 'Spring Boot 自动装配通过 `@EnableAutoConfiguration` 导入 `AutoConfigurationImportSelector`。在应用启动时，该 Selector 读取所有 jar 包中 `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`（Spring Boot 3.x）或 `spring.factories`（2.x）中配置的自动配置类列表。然后结合各自动配置类上的条件注解（如 `@ConditionalOnClass`、`@ConditionalOnMissingBean`、`@ConditionalOnProperty`）进行条件筛选，仅在符合当前运行环境依赖时才将对应的 Bean 注入 Spring 容器，实现“约定大于配置、开箱即用”。', '自动装配,自动配置,EnableAutoConfiguration,spring.factories,条件注解,ConditionalOnClass,SpringBoot原理', 'Spring与微服务', 1, 'it-118', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (119, '@SpringBootApplication 注解由哪三个核心注解组合而成？各自作用是什么？', '`@SpringBootApplication` 是一个复合注解，核心由以下三者组合而成：1. `@SpringBootConfiguration`：继承自 `@Configuration`，标识当前类为配置类，可向容器注册 Bean；2. `@EnableAutoConfiguration`：开启 Spring Boot 的自动装配机制，根据 classpath 依赖智能加载预置组件；3. `@ComponentScan`：配置组件扫描路径，默认扫描当前启动类所在包及其所有子包下的 `@Component`、`@Service`、`@Repository`、`@Controller` 等注解并注册为 Bean。', 'SpringBootApplication,SpringBoot,注解,核心注解,组合注解,注解组成,SpringBootConfiguration,EnableAutoConfiguration,ComponentScan', 'Spring与微服务', 1, 'it-119', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (120, 'Spring Cloud 微服务体系的核心组件有哪些？各自承担什么职责？', '主流 Spring Cloud 微服务核心包括 5 大模块：1. 服务注册与发现中心（Nacos / Eureka / Consul）：负责微服务实例的元数据登记、心跳健康检查与动态服务发现；2. 服务网关（Spring Cloud Gateway）：作为全站流量统一入口，提供路由转发、统一鉴权、限流与跨域处理；3. 声明式远程调用（OpenFeign）：基于注解与 HTTP 的客户端声明式 RPC 通信；4. 熔断降级与流量防护（Sentinel / Resilience4j）：提供高并发防雪崩、流量整形、热点参数限流；5. 分布式配置中心（Nacos Config / Spring Cloud Config）：统一集中管理各服务配置并支持动态热刷新。', 'SpringCloud,微服务,微服务体系,微服务架构,核心组件,组件,组件有哪些,分布式架构', 'Spring与微服务', 1, 'it-120', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (121, 'Nacos 作为注册中心和配置中心的核心工作原理是什么？与 Eureka 有何不同？', '1. 服务注册：客户端启动时向 Nacos 发送 HTTP/gRPC 请求上报服务元数据，临时实例通过心跳周期上报健康状态（5s一次），持久实例由服务端主动探活。Nacos 服务端采用 Copy-On-Write 内存列表管理实例变更并通过 UDP/gRPC 实时推送给订阅方；2. 配置中心：客户端采用基于长轮询（Long Polling）与 gRPC 的监听机制，配置变更时 MD5 校验不匹配则主动拉取最新内容并刷新环境上下文。对比 Eureka：Eureka 只支持 AP 模型与轮询同步；Nacos 同时支持 CP（Raft协议）和 AP（Distro协议）动态切换，具备更高的性能与动态推送能力。', 'Nacos,注册中心,配置中心,长轮询,心跳机制,Eureka对比,AP模式,CP模式,动态刷新', 'Spring与微服务', 1, 'it-121', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (122, '微服务间远程调用 OpenFeign 的底层通信原理与超时重试配置是怎样的？', 'OpenFeign 是一个声明式 HTTP 客户端。原理：启动时扫描带有 `@FeignClient` 注解的接口，通过 JDK 动态代理生成代理对象；执行方法时将方法参数解析为 HTTP 请求报文（RequestTemplate），集成 Ribbon / Spring Cloud LoadBalancer 进行客户端负载均衡，最后交由底层 HTTP 客户端（默认 HttpURLConnection，生产推荐替换为 Apache HttpClient 或 OkHttp 开启连接池）发送真实网络请求。关键配置包括 connectTimeout（建联超时）、readTimeout（读取超时）以及自定义 Feign.Retryer 重试器。', 'OpenFeign,远程调用,Feign,负载均衡,HTTP客户端,超时重试,连接池,RPC', 'Spring与微服务', 1, 'it-122', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (123, '微服务容错降级中，Sentinel 与 Hystrix 有什么区别？滑动窗口原理是怎样的？', 'Hystrix 已停止维护，主要基于线程池隔离或信号量隔离，每个接口独立分配线程池开销大。Sentinel 是阿里开源的流量治理组件：1. 资源隔离：基于信号量隔离与调用链路上下文，内存开销极小；2. 熔断策略：支持慢调用比例、异常比例、异常数多种维度自动降级；3. 滑动时间窗口（LeapArray）：将统计周期切分为多个微时间小格（WindowBucket），窗口随时间推进滑动丢弃过期小格，利用原子累加精确统计高频 QPS 与 RT 异常。', 'Sentinel,Hystrix,熔断降级,滑动窗口,流量防护,熔断器,限流', 'Spring与微服务', 1, 'it-123', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (124, 'Spring Cloud Gateway 核心架构与过滤器链（Filter Chain）执行流程是怎样的？', 'Spring Cloud Gateway 基于 Spring 5、Project Reactor 和 Netty 开发，采用响应式非阻塞异步架构。核心由三大要素构成：Route（路由定义：ID、目标 URI、断言集合、过滤器集合）、Predicate（断言：匹配 HTTP 请求的 Path、Method、Header 等条件）、Filter（过滤器：对请求和响应进行拦截和改写）。执行流程：请求到达 ➔ 路由匹配 HandlerMapping ➔ 构建责任链式 WebFilter 链 ➔ 依次执行 Pre 过滤器 ➔ Netty 发送代理请求 ➔ 依次执行 Post 过滤器 ➔ 返回客户端响应。', 'SpringCloudGateway,网关,过滤器链,断言,Predicate,Route,Netty,响应式', 'Spring与微服务', 1, 'it-124', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (125, 'MySQL InnoDB 存储引擎与 MyISAM 引擎的核心区别是什么？', '核心区别：1. 事务支持：InnoDB 支持 ACID 事务，具备回滚机制；MyISAM 不支持事务；2. 锁粒度：InnoDB 支持行级锁（行锁配合索引）和表锁，并发写入能力强；MyISAM 仅支持表锁，写操作会阻塞所有读写；3. 灾难恢复：InnoDB 拥有 redo log 与 undo log，具备崩溃安全恢复（Crash-Safe）；MyISAM 宕机易损坏数据表；4. 外键支持：InnoDB 原生支持外键关联约束；MyISAM 不支持；5. 存储方式：InnoDB 是聚簇索引（数据和主键索引存放在同一个 ibd 文件）；MyISAM 是非聚簇索引（索引文件 MYI 与数据文件 MYD 分开存储）。', 'InnoDB,MyISAM,存储引擎,行级锁,表锁,事务支持,崩溃恢复,聚簇索引', 'MySQL与数据存储', 1, 'it-125', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (126, 'MySQL 索引为什么选择 B+ 树而不是 B 树、哈希表或红黑树？', '1. 对比哈希表：哈希表等值查询 O(1) 极快，但无法支持范围查询（`BETWEEN`、`>`、`<`）和排序（`ORDER BY`）；2. 对比二叉树/红黑树：二叉树每个节点只有两个子节点，树的高度极深，高数据量下磁盘 I/O 次数巨大；3. 对比 B 树：B 树所有节点都存储键和数据行，导致每个磁盘页能容纳的索引键数量较少，树的高度增加。而 B+ 树的非叶子节点只存储索引键不存数据，单页可容纳千余个索引项，3 层 B+ 树即可索引千万级数据；且叶子节点包含所有数据并通过双向链表相连，极大提升了范围扫描与全表遍历性能。', 'B+树,B树,索引原理,二叉树,红黑树,哈希索引,范围查询,磁盘IO', 'MySQL与数据存储', 1, 'it-126', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (127, '什么是聚簇索引与非聚簇索引（二级索引）？什么是回表查询？', '1. 聚簇索引（Clustered Index）：InnoDB 中按照主键构建的 B+ 树，其叶子节点存储了完整的行记录数据（索引与数据即为一体），一张表有且仅有一个聚簇索引；2. 二级索引（Secondary Index）：由普通字段建立的索引，其叶子节点只存储该字段值及对应的主键值；3. 回表查询：当通过二级索引查询时，先在二级索引树查到主键 ID，再拿主键 ID 回到聚簇索引树查找整行数据，多经历一次树查询即为“回表”。可通过“覆盖索引”消除回表以优化性能。', '聚簇索引,非聚簇索引,二级索引,回表查询,覆盖索引,主键索引', 'MySQL与数据存储', 1, 'it-127', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (128, '什么是覆盖索引与最左前缀原则？如何避免常见的索引失效？', '覆盖索引是指查询语句所需要的字段列全部存在于所使用的索引树中，无需回表。最左前缀原则指在联合索引 `(a, b, c)` 中，查询条件必须从最左列开始连续匹配，否则无法使用后续索引。常见索引失效场景：1. 在索引列上做函数运算、数学计算或隐式类型转换（如数字与字符串未加引号）；2. 使用非最左前缀或跳过联合索引前置列；3. 以通配符 `%` 开头的 LIKE 模糊查询（如 `%keyword`）；4. OR 关联的字段中有一方未建立索引；5. 不等于（`!=` 或 `<>`）及特定 `NOT IN` 导致的全表扫描更优选择。', '覆盖索引,最左前缀原则,索引失效,联合索引,隐式转换,like模糊查询', 'MySQL与数据存储', 1, 'it-128', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (129, 'MySQL 事务的 ACID 特性分别是什么？底层是如何保证的？', 'ACID 特性：1. 原子性（Atomicity）：事务内操作要么全成功要么全回滚，由 `undo log`（回滚日志）保证；2. 一致性（Consistency）：数据从一个合法状态转变到另一个合法状态，是事务追求的最终目标；3. 隔离性（Isolation）：多个并发事务相互独立隔离，由锁机制（Record Lock, Gap Lock）与 `MVCC` 多版本并发控制保证；4. 持久性（Durability）：事务一旦提交其变更永久保存在磁盘，由 `redo log`（重做日志）与 WAL（Write-Ahead Logging 先写日志后写盘）机制保证。', 'MySQL,MySQL事务,事务,ACID,ACID特性,特性,原子性,一致性,隔离性,持久性,redolog,undolog,WAL', 'MySQL与数据存储', 1, 'it-129', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (130, 'MySQL 事务的四种隔离级别是什么？分别解决了什么并发读问题？', 'SQL 标准定义的四种隔离级别：1. 读未提交（Read Uncommitted）：最低级别，会产生脏读（Dirty Read）、不可重复读、幻读；2. 读已提交（Read Committed）：解决脏读，每次 SELECT 读取生成新的 ReadView，仍存在不可重复读和幻读（Oracle 默认）；3. 可重复读（Repeatable Read）：解决脏读和不可重复读，事务内首次 SELECT 生成 ReadView 并贯穿始终，配合 Next-Key Lock 基本解决幻读（MySQL InnoDB 默认）；4. 串行化（Serializable）：强制事务串行执行，完全解决所有并发问题，但并发性能极低。', 'MySQL,MySQL事务,事务,事务隔离级别,隔离级别,四种隔离级别,读未提交,读已提交,可重复读,串行化,脏读,幻读', 'MySQL与数据存储', 1, 'it-130', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (131, '什么是 MVCC（多版本并发控制）？ReadView 是如何实现快照读的？', 'MVCC 是在不加锁的情况下提升数据库读写并发性能的机制。实现依赖于每行记录的 3 个隐藏字段（DB_TRX_ID 事务ID、DB_ROLL_PTR 回滚指针、DB_ROW_ID）、undo log 版本链以及 ReadView（读视图）。ReadView 包含当前活跃未提交事务 ID 列表（m_ids）、最小活跃事务 ID（min_trx_id）、最大已分配事务 ID（max_trx_id）及创建者事务 ID（creator_trx_id）。事务读取时沿 undo log 版本链向前比对：若版本的 trx_id 小于 min_trx_id 或等于 creator_trx_id 则可见；若大于等于 max_trx_id 或在 m_ids 中则不可见，依此找到该事务可见的历史版本。', 'MVCC,多版本并发控制,ReadView,快照读,undolog版本链,隐藏字段,trx_id', 'MySQL与数据存储', 1, 'it-131', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (132, 'MySQL 中的当前读与快照读有什么区别？Next-Key Lock 是如何解决幻读的？', '1. 快照读（Snapshot Read）：普通的 `SELECT` 查询，通过 MVCC 读取记录的历史快照版本，不加锁，非阻塞；2. 当前读（Current Read）：如 `SELECT ... FOR UPDATE`、`LOCK IN SHARE MODE`、`UPDATE`、`DELETE`，读取的是记录的最新版本，并且必须对读取的记录加锁。InnoDB 在可重复读级别下，当前读通过 `Next-Key Lock`（行记录锁 Record Lock + 间隙锁 Gap Lock）将记录本身及其两侧的开区间间隙锁死，阻止其他事务向间隙内插入新数据（INSERT 阻塞），从而彻底杜绝了当前读场景下的幻读问题。', '当前读,快照读,NextKeyLock,间隙锁,GapLock,行锁,解决幻读', 'MySQL与数据存储', 1, 'it-132', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (133, 'MySQL 慢 SQL 常见排查定位方法与 EXPLAIN 执行计划关键指标分析', '排查流程：1. 开启慢查询日志（`slow_query_log=ON`, 设定 `long_query_time` 阈值）；2. 借助 `mysqldumpslow` 或监控工具汇总分析高频慢查询；3. 使用 `EXPLAIN` 分析执行计划。核心指标：- `type`：访问类型，性能由好到差为 system > const > eq_ref > ref > range > index > ALL（ALL为全表扫描，原则上必须优化至 range/ref 以上）；- `key`：实际使用的索引；- `rows`：预估扫描行数；- `Extra`：包含 `Using filesort`（文件排序）或 `Using temporary`（使用临时表）时需重点优化，出现 `Using index` 表示覆盖索引。', '慢SQL,EXPLAIN,执行计划,type,Extra,慢查询日志,索引优化,全表扫描', 'MySQL与数据存储', 1, 'it-133', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (134, 'MySQL 主从复制的底层工作原理是什么？如何解决主从复制延迟问题？', '主从复制分为 3 步：1. 主库在事务提交时将数据变更记录写入 Binary Log（binlog）；2. 从库通过 I/O 线程连接主库，请求并接收 binlog 内容写入本地 Relay Log（中继日志）；3. 从库 SQL 线程读取 Relay Log 并回放 SQL 实现数据同步。binlog 常见格式有 Statement、Row（推荐，记录行变动，无函数不确定性）和 Mixed。解决主从延迟：1. 开启从库多线程并行复制（MTS）；2. 从库升级 SSD 硬件；3. 核心强一致性业务（如支付订单刚写入后的立即查询）强制路由走主库查询。', 'MySQL,主从复制,主从同步,从库延迟,主从延迟,复制原理,binlog,RelayLog,多线程复制,Row格式', 'MySQL与数据存储', 1, 'it-134', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (135, '数据库分库分表的拆分维度有哪些？ShardingSphere 核心架构与原理是什么？', '拆分维度：1. 垂直拆分：垂直分库（按微服务业务领域拆分库，如用户库、课程库、订单库）、垂直分表（大表冷热字段分离，将大文本列拆出）；2. 水平拆分：水平分表/分库（单表数据量过亿，按 Hash 取模、时间范围或租户 ID 将行数据打散到多个物理库表）。Apache ShardingSphere 是开源分布式数据库中间件生态，核心包含 SQL 解析、路由计算（按分片键确定物理节点）、SQL 改写（改写逻辑表名为真实物理表名）、执行器并发执行与结果集合并（排序、分页、聚合函数归并）。', '分库分表,ShardingSphere,水平拆分,垂直拆分,分片键,路由改写,读写分离', 'MySQL与数据存储', 1, 'it-135', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (136, '乐观锁与悲观锁在数据库中的实现方式与应用场景是什么？', '1. 悲观锁（Pessimistic Lock）：假定并发冲突概率极高，每次访问数据前都显式加排他锁。数据库层面通过 `SELECT ... FOR UPDATE` 实现，其他事务试图修改或加锁时将被挂起阻塞，适用于写多读少、强一致性要求的金融账务扣款场景；2. 乐观锁（Optimistic Lock）：假定并发冲突极低，操作数据时不加锁，仅在更新提交时核验版本。常用方式是在表中增加 `version` 整数列，更新时执行 `UPDATE table SET val = ?, version = version + 1 WHERE id = ? AND version = old_version`，若受影响行数为 0 则触发重试或失败，适用于读多写少的高并发电商秒杀扣库存场景。', '乐观锁,悲观锁,version版本号,FORUPDATE,CAS,并发冲突,排他锁', 'MySQL与数据存储', 1, 'it-136', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (137, 'Redis 为什么速度这么快？单线程模型为什么能支撑高并发？', '核心原因：1. 内存存储：数据全部存储在内存中，内存读写速度（纳秒级）是机械/固态磁盘（微秒/毫秒级）的数千倍；2. 高效数据结构：专门优化底层编码（如 SDS 简单动态字符串、跳表 SkipList、压缩列表 ListPack）；3. 单线程无锁开销：核心命令执行由单主线程完成，彻底消除了多线程上下文切换、CPU 核心争抢及复杂的加锁解锁开销；4. I/O 多路复用：基于 Linux epoll 的非阻塞 I/O 事件驱动模型，单个线程即可高效并发监听数万个客户端网络连接。注：Redis 6.0 引入了多线程网络 I/O 解析，但命令执行核心依然保持单线程。', 'Redis,速度快,单线程,单线程模型,为什么快,多路复用,epoll,内存存储,高并发原因', 'Redis与高性能缓存', 1, 'it-137', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (138, 'Redis 五种常用基础数据结构底层编码实现是怎样的？', '1. String：底层为 SDS（Simple Dynamic String），记录长度 len 与空闲空间，O(1) 获取长度且二进制安全；2. List：双向链表或 QuickList（压缩列表 + 双向链表组合）；3. Hash：元素少时采用 ZipList/ListPack，元素多或单个值长时转为 HashTable 字典；4. Set：整数集合 IntSet（全数字且数量少）或 HashTable（Value 为 null 的字典）；5. ZSet（有序集合）：元素少时使用 ZipList，元素多时使用【跳表 SkipList + 字典 HashTable】联合实现，兼顾 O(log n) 范围查询与 O(1) 分值查询。', 'Redis,数据结构,底层实现,基础数据结构,底层编码,SDS,跳表,QuickList,ZipList,HashTable', 'Redis与高性能缓存', 1, 'it-138', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (139, '什么是缓存穿透、缓存击穿、缓存雪崩？各自的最佳解决方案是什么？', '1. 缓存穿透：大量请求查询数据库中根本不存在的数据（如非法 ID），请求直穿底层 DB 导致崩溃。方案：接口参数合法性校验、缓存空对象（设置短 TTL 1~5分钟）、布隆过滤器（Bloom Filter）前置快速拦截；2. 缓存击穿：单个热点 Key（高并发访问）在某一瞬间过期失效，海量请求同时并发穿透查 DB 重建缓存。方案：互斥排他锁（setnx）保证单线程重建、热点数据设置逻辑永不过期并在后台异步刷新；3. 缓存雪崩：大量不同 Key 在同一时间集中过期，或 Redis 服务节点宕机导致所有请求涌入 DB。方案：过期时间加上随机抖动偏移量（如 TTL + Random(1~5min)）、搭建 Redis 主从哨兵高可用集群、配置降级与限流。', '缓存穿透,缓存击穿,缓存雪崩,布隆过滤器,互斥锁,随机过期时间,缓存高可用', 'Redis与高性能缓存', 1, 'it-139', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (140, 'Redis 分布式锁是如何实现的？为什么必须配合 Lua 脚本保证原子性？', '标准实现：`SET lock_key unique_value NX PX 30000`。其中 `NX` 保证只有 key 不存在时才能设置成功（互斥加锁），`PX` 设置过期时间毫秒数防死锁。释放锁时必须核对 `unique_value` 与当前客户端生成的 UUID 是否一致，防止 A 客户端业务超时后释放了 B 客户端新获得的锁。比对 value 与删除 key 是两步操作，必须通过 Lua 脚本执行（`if redis.call("get", KEYS[1]) == ARGV[1] then return redis.call("del", KEYS[1]) else return 0 end`），利用 Redis 单线程执行 Lua 脚本的不可中断性确保释放锁的原子性。针对锁续期需求可引入 Redisson 看门狗（Watchdog）机制。', '分布式锁,Redis锁,Lua脚本,原子性,SETNX,看门狗,Redisson,防死锁', 'Redis与高性能缓存', 1, 'it-140', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (141, 'Redis Redlock（红锁）算法的原理是什么？为什么业界存在争议？', 'Redlock 是 Redis 官方提出的在多独立主节点集群下的分布式锁算法。原理：客户端依次向 N 个（通常为 5 个）互相独立的 Redis 实例请求加锁；当且仅当在大多数（N/2 + 1 = 3个）实例上加锁成功，且获取锁耗费的总时间小于锁有效时间时，才认为加锁成功。争议：分布式权威 Martin Kleppmann 曾指出，Redlock 高度依赖物理系统的系统时钟（NTP 时钟跳跃会导致锁过早失效），且无法解决长垃圾回收（STW GC）或网络分区导致的并发竞态安全问题；若对分布式一致性要求极高，更推荐基于强一致性共识协议的 ZooKeeper 或 etcd。', 'Redlock,红锁,分布式锁算法,时钟漂移,Martin争论,etcd对比,高可用锁', 'Redis与高性能缓存', 1, 'it-141', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (142, 'Redis 数据持久化机制：RDB 与 AOF 的原理、优缺点及混合持久化', '1. RDB（快照）：定时将内存完整数据集以二进制压缩格式写入 dump.rdb 文件。通过 `bgsave` fork 出子进程进行写时复制（COW）。优点：恢复大数据集极快，文件紧凑；缺点：非实时，宕机丢失最后一次快照后的所有数据；2. AOF（追加日志）：将每个写命令记录到 appendonly.aof。支持 everysec（每秒刷盘，推荐）、always 与 no。优点：数据安全度高；缺点：文件体积大，恢复慢；3. 混合持久化（4.0+）：AOF 重写时将前半段快照保存为 RDB 格式，后半段增量指令以 AOF 追加，兼具 RDB 的极速恢复与 AOF 的低丢数据优势。', 'RDB,AOF,持久化,混合持久化,写时复制,COW,bgsave,appendfsync', 'Redis与高性能缓存', 1, 'it-142', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (143, 'Redis 内存淘汰策略（Eviction Policies）有哪些？LRU 与 LFU 有何区别？', '当内存达到 `maxmemory` 上限时触发淘汰。包含 8 种策略：1. noeviction（默认）：拒绝写入并报错；2. volatile-lru：从设置了过期时间的 key 中淘汰最近最少使用；3. allkeys-lru：从所有 key 中淘汰最近最少使用；4. volatile-lfu：淘汰最不经常使用（频次最低）；5. allkeys-lfu：从所有 key 中淘汰最不经常使用；6. volatile-random / allkeys-random：随机淘汰；7. volatile-ttl：淘汰剩余 TTL 最短的 key。区别：LRU（Least Recently Used）关注最后一次访问时间；LFU（Least Frequently Used）关注访问频率计数（利用半衰期降权），更能真实反映热点数据的持久价值。', '内存淘汰策略,LRU,LFU,maxmemory,淘汰算法,noeviction,热点数据', 'Redis与高性能缓存', 1, 'it-143', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (144, 'Redis 过期键删除策略有哪些？惰性删除与定期删除如何协同？', 'Redis 采用【惰性删除 + 定期删除】协同机制：1. 惰性删除（Lazy Free）：当客户端访问某个 key 时，Redis 检查其是否过期，若过期则立即删除并返回 nil。优点：CPU 友好，不浪费算力去轮询；缺点：若大量过期 key 永远不再被访问，会长期白白占用内存；2. 定期删除（Active Expire）：Redis 默认每秒运行 10 次后台定时任务（serverCron），随机抽取一定数量（如20个）带 TTL 的 key 进行检查，若过期比例超过 25% 则继续循环清理。两者结合在 CPU 开销与内存回收率之间取得了最佳平衡。', '过期删除,惰性删除,定期删除,TTL过期,内存回收,serverCron', 'Redis与高性能缓存', 1, 'it-144', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (145, 'Redis 主从复制、哨兵模式（Sentinel）与集群模式（Cluster）的区别与选型', '1. 主从复制（Replication）：单主多从，主写从读，实现读写分离扩展读 QPS，但主节点宕机无法自动故障转移；2. 哨兵模式（Sentinel）：由独立哨兵集群对主从节点进行心跳监控、自动选主与故障转移（Failover），通知客户端新主地址，解决了高可用问题，但单个 Master 仍然受限于单机内存与写性能瓶颈；3. 集群模式（Cluster）：分布式分片架构，支持多主多从，通过 16384 个哈希槽将写请求水平扩展到多台物理机器，支持海量数据存储与超大规模高并发写，是大规模企业级首选架构。', 'Redis,主从复制,哨兵模式,哨兵,Sentinel,集群,Cluster,集群模式,选型对比,高可用', 'Redis与高性能缓存', 1, 'it-145', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (146, 'Redis Cluster 集群的哈希槽（Hash Slot）机制与数据分片原理', 'Redis Cluster 预置了固定数量的 `16384` 个哈希槽（Slots：0 ~ 16383）。每个 Master 节点负责管理其中一部分连续或离散的槽位。当执行键值操作时，客户端或服务端通过 CRC16 校验和对 key 计算哈希值并对 16384 取模：`slot = CRC16(key) & 16383`。若 key 包含 `{hash_tag}`，则仅对花括号内的字符串进行哈希，确保相关联的多个 key 映射到同一个哈希槽和节点。若客户端请求的 key 不在当前节点负责的槽位，节点返回 `-MOVED slot ip:port` 重定向指引客户端跳转访问正确节点。', 'Redis,Cluster,哈希槽,HashSlot,slot,16384,CRC16,集群分片,重定向', 'Redis与高性能缓存', 1, 'it-146', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (147, '如何保证 Redis 缓存与 MySQL 数据库的双写一致性？（Cache Aside Pattern）', '最经典的工业界模式为 Cache Aside Pattern（旁路缓存模式）：1. 读取：先查缓存，命中则返回；未命中则查数据库，将结果写入缓存并返回；2. 更新：先更新数据库，再删除缓存（而非直接更新缓存）。为什么删除而非更新：避免高并发并发写导致缓存脏数据覆盖，且删除是惰性计算更为节省。为什么先更 DB 再删 Cache：产生不一致概率极低。若需要极限强一致性，可结合【延迟双删】（先删缓存 ➔ 改库 ➔ 休眠几百毫秒 ➔ 再次删缓存）或基于阿里开源 Canal 监听 MySQL binlog 异步消费消息重试删除缓存。', 'Redis,MySQL,双写一致性,双写一致,缓存双写,双写,一致性,CacheAside,旁路缓存,延迟双删,Canal', 'Redis与高性能缓存', 1, 'it-147', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (148, 'Redis 常见性能瓶颈分析：BigKey（大Key）与 HotKey（热Key）的排查及解决方案', '1. BigKey（体积或元素量超大）：危害在于单线程阻塞、网络带宽耗尽及删除时引发 STW。排查：`redis-cli --bigkeys` 或分析 RDB。解决：拆分大 Key、禁用全量读取操作（如禁 keys * 改用 scan，hgetall 改用 hscan）、异步非阻塞删除（`UNLINK` 命令代替 `DEL`）；2. HotKey（瞬间访问 QPS 极高）：危害在于瞬时流量打爆单个 Redis 分片网卡。排查：`redis-cli --hotkeys` 或利用客户端代理层统计。解决：在应用本地添加多级缓存（Caffeine / Guava Cache）、将热 Key 加上随机后缀分散存储到多个 Redis 分片节点。', 'BigKey,HotKey,大Key,热Key,UNLINK,Caffeine,本地缓存,Redis调优', 'Redis与高性能缓存', 1, 'it-148', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (149, '消息队列（MQ）的核心应用场景有哪些？各自解决什么业务痛点？', '三大核心价值场景：1. 异步解耦：将耗时较长、非核心链路从主流程中剥离（如用户注册成功后异步发送短信通知、赠送新人礼包，主业务立即返回成功响应，系统间不再直接依赖 API）；2. 流量削峰填谷：在电商大促秒杀或技术活动抢购场景下，瞬时并发请求可能超出数据库承载极限，消息队列作为蓄水池暂存海量请求，后台消费者按自身处理能力平稳匀速拉取消费；3. 系统广播与事件驱动：一个业务事件（如订单支付完成）触发多个下游子系统（库存扣减、发票生成、风控积分）并发监听处理。', '消息队列,应用场景,异步处理,系统解耦,削峰填谷,高并发秒杀,事件驱动', '消息队列与中间件', 1, 'it-149', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (150, '主流消息队列选型对比：Kafka、RocketMQ 与 RabbitMQ 优缺点与适用场景', '1. Kafka：基于 Scala/Java，百万级 TPS 吞吐量极致，支持分区并行、零拷贝与页面缓存，生态成熟，非常适合大数据日志收集、指标监控与流式实时计算；2. RocketMQ：阿里开源顶级项目，支持几十万 TPS，采用 Java 原生编写，功能特性极为丰富（支持严格顺序消息、定时延时消息、分布式事务消息、亿级消息堆积），是国内大型电商与互联网核心业务系统首选；3. RabbitMQ：基于 Erlang 语言，万级 TPS，基于 AMQP 协议，支持灵活丰富的交换机（Exchange）路由拓扑，管理后台直观友好，时延极低（微秒级），适合中小企业中敏捷快速业务开发。', 'MQ选型,Kafka,RocketMQ,RabbitMQ,对比,吞吐量,延迟队列,事务消息', '消息队列与中间件', 1, 'it-150', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (151, 'Kafka 为什么具有极高的吞吐量？零拷贝（Zero-Copy）机制是怎样的？', '高吞吐核心架构支撑：1. 顺序写磁盘：Kafka 采用追加日志（Append-only log）方式写入文件，顺序写速度接近甚至超过内存随机读写；2. PageCache 页面缓存：充分利用 Linux 操作系统缓存，尽可能在内存中完成读写，避免频繁下发磁盘 I/O；3. 零拷贝技术（Zero-Copy）：消费数据时采用 Linux 系统调用 `sendfile`，数据直接从 OS PageCache 传输到网卡缓冲区，完全跳过用户态内存拷贝与 CPU 上下文切换；4. 分区并发（Partition）：一个 Topic 拆分多个 Partition，各 Broker 节点独立并发读写；5. 批量压缩（Batch Compression）：多条小消息打包合并压缩发送。', 'Kafka,高吞吐,高吞吐量,零拷贝,ZeroCopy,sendfile,PageCache,顺序写盘,吞吐量', '消息队列与中间件', 1, 'it-151', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (152, 'Kafka 的消息分区（Partition）与消费者组（Consumer Group）机制是怎样的？', '1. 分区（Partition）：Topic 在物理上的并行切片，是 Kafka 并发与横向扩容的基本单元，单个 Partition 内消息严格保序且具备单调递增的 Offset 偏移量；2. 消费者组（Consumer Group）：实现发布-订阅与点对点两种模型的关键。同一消费者组内的多个消费者共同协作消费该 Topic 的所有分区，但【一个 Partition 同时只能被同一个 Group 内的某一个 Consumer 消费】；不同 Group 之间互不干扰。当消费者上线或宕机时，会触发 Rebalance（再均衡）重新分配分区所有权。', 'Partition,分区,消费者组,ConsumerGroup,Rebalance,Offset,负载均衡', '消息队列与中间件', 1, 'it-152', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (153, '消息队列如何保证消息的绝对顺序性（顺序消费）？', '保证顺序必须做到“生产顺序 ➔ 队列顺序 ➔ 消费顺序”三环节闭环：1. 生产端：将需要保序的消息指定同一个业务 Key（如同一笔订单的创建、支付、发货），确保消息通过 Hash 算法路由写入同一个 Partition 或 MessageQueue；2. 存储端：单个 Partition / MessageQueue 内部天然是有序追加写入的单向队列；3. 消费端：单个 Partition 只能由单个消费线程单线程拉取消费，消费端禁止多线程异步乱序处理同一 Partition 的消息。若需要并行，可在内存中按业务 Key 再次哈希分发给不同的内部工作队列执行。', '消息队列,顺序消费,顺序消息,消息顺序,保序,局部有序,分区有序,MessageQueue', '消息队列与中间件', 1, 'it-153', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (154, '消息队列如何保证消息不丢失？高可靠投递与持久化机制是怎样的？', '必须防范三处丢失点：1. 生产端防丢：采用同步发送或带回调的异步发送，配置 ACK 参数（Kafka 设置 `acks=all` 或 `-1`），要求主副本与所有 ISR 同步副本全部确认写入后才算成功，否则自动重试；2. Broker 端防丢：开启持久化刷盘机制，Kafka 配置高可靠多副本机制（`min.insync.replicas >= 2`），RocketMQ 采用同步双写（SYNC_MASTER）；3. 消费端防丢：关闭自动提交 Offset（如 Kafka 设置 `enable.auto.commit=false`），待业务逻辑真正执行成功并且入库后再显式手动提交 ACK / Offset。', '消息队列,消息丢失,防止丢失,防丢失,消息不丢失,高可靠投递,高可靠,手动ACK,acks=all', '消息队列与中间件', 1, 'it-154', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (155, '消息队列如何处理消息重复消费？消费幂等性如何设计？', '由于网络闪断、超时重试或 Rebalance，消息重复投递是分布式系统的常态，因此消费端必须具备【幂等性（Idempotency）】。常用方案：1. 唯一业务流水号（如订单号 + 业务类型），消费前先查数据库或 Redis 判断该记录是否已处理过；2. 数据库唯一键约束（Unique Key）：利用主键冲突或唯一索引直接防御并发插入重复记录；3. 状态机防重：在订单状态流转中采用前置条件控制（如 `UPDATE t_order SET status=2 WHERE id=? AND status=1`），状态已跃迁则受影响行数为 0，天然防重；4. 分布式锁防并发消费。', '重复消费,消费幂等性,幂等设计,唯一业务号,唯一键,状态机防重,防重复', '消息队列与中间件', 1, 'it-155', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (156, '如何处理消息队列中的消息积压（Backlog）问题？排查思路与应急扩容方案', '积压根本原因是：生产速度长期远高于消费速度，或下游消费者发生慢 SQL、死锁、依赖下游服务超时崩溃。应急处理步骤：1. 先紧急修复消费端 Bug 或调整下游限流阈值恢复消费能力；2. 紧急扩容方案：临时停掉原消费者进程，建立一个临时的中转 Topic 并创建数十倍于原分区的临时 Partition，编写临时分发消费者仅做快速中转转发，将积压消息瞬间平摊到几十个新分区中，再起几十倍的新消费者集群并发快速消化；3. 长期治理：优化消费端耗时逻辑、引入批量消费、提升消费线程数。', '消息队列,消息积压,积压,堆积,消息堆积,消费慢,应急扩容,Backlog,消息治理', '消息队列与中间件', 1, 'it-156', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (157, 'RocketMQ 事务消息（半消息机制）的执行原理是怎样的？', '基于两阶段提交思想：1. 发送方首先向 RocketMQ 发送一条【半消息（Half Message）】，该消息对消费者不可见；2. 半消息发送成功后，发送方执行本地数据库事务（如本地订单落库）；3. 根据本地事务执行结果，发送方发送二次确认指令：提交（Commit，使消息对下游可见）或回滚（Rollback，丢弃该消息）；4. 若网络异常二次确认丢失，RocketMQ 服务端会发起定时【消息回查（Check）】，调用发送方提供的回查接口检查本地事务真实状态，并依据结果最终决定提交或回滚，实现跨系统的最终一致性。', 'RocketMQ,事务消息,半消息,HalfMessage,两阶段提交,消息回查,最终一致性', '消息队列与中间件', 1, 'it-157', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (158, 'RabbitMQ 延时队列的实现原理是怎样的？（TTL + 死信交换机 DLX）', '原生 RabbitMQ 常用【TTL 消息存活时间 + DLX 死信交换机】实现延时：1. 创建一个正常业务队列，不设置消费者，为其配置消息过期时间（`x-message-ttl`），并绑定死信交换机（`x-dead-letter-exchange`）与死信 RoutingKey；2. 生产者向该队列发送待延时消息；3. 当消息在队列中等待超时未被消费，自动变为死信（Dead Letter）；4. RabbitMQ 自动将死信路由投递至绑定的死信交换机，并进入延时目标队列由实际工作消费者处理，从而达到定时延时触发效果；亦可使用官方 `rabbitmq-delayed-message-exchange` 插件实现。', '延时队列,RabbitMQ,死信队列,DLX,TTL,死信交换机,定时任务', '消息队列与中间件', 1, 'it-158', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (159, 'Vue 3 相比 Vue 2 有哪些核心改进与重大优势？', '核心突破：1. 响应式系统重构：由 `Object.defineProperty` 改为原生 `Proxy`，完美支持监听对象属性动态新增/删除及数组下标变动，无需 `$set`，内存与性能大幅提升；2. 组合式 API（Composition API）：解决 Vue 2 Options API 在复杂大型组件中逻辑碎片化问题，按业务关注点组织代码，极大增强逻辑复用（Custom Hooks）；3. 性能与体积：基于编译时标记（Patch Flags）、静态节点提升（Hoist Static）优化 Virtual DOM Diff 速度；支持彻底的 Tree-shaking 使得打包体积精简 40% 以上；4. 更好的 TypeScript 原生支持。', 'Vue3,Vue2,对比,Proxy,CompositionAPI,响应式重构,TreeShaking,PatchFlag', '前端与全栈工程', 1, 'it-159', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (160, 'Vue 3 的响应式原理是怎样的？Proxy 与 Reflect 是如何配合实现的？', 'Vue 3 核心基于 ES6 `Proxy` 进行对象代理拦截，并在 `get` 与 `set` 捕获器中配合 `Reflect` 操作：1. 依赖收集（Track）：当访问对象属性时触发 `get`，在 `track()` 中将当前激活的副作用函数（`activeEffect`）与该对象的属性键（target ➔ key ➔ dep）建立映射关系放入 WeakMap；2. 派发更新（Trigger）：当修改对象属性时触发 `set`，在 `trigger()` 中找到该属性对应的所有 dep 副作用函数并依次重新执行。配合 `Reflect` 保证了 `this` 指向正确（避免原型链继承时 this 指向代理前原始对象的 Bug）并返回操作布尔值。', 'Vue3,Proxy,响应式,响应式原理,Reflect,依赖收集,派发更新,track,trigger,WeakMap', '前端与全栈工程', 1, 'it-160', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (161, 'Vue 3 中 ref 和 reactive 的区别与使用场景是什么？为什么 ref 需要 .value？', '1. 数据类型支持：`ref` 可包裹基本数据类型（如 number, string, boolean）及引用对象；`reactive` 只能接收复杂对象或数组；2. 底层实现：`ref` 对于基本类型封装了一个带有 `get value()` 和 `set value()` 访问器属性的 `RefImpl` 对象，因此在 JS 代码中必须通过 `.value` 访问与修改（模板中会自动脱钩解包）；对于对象类型，ref 底层仍然调用 reactive 进行 Proxy 代理；3. 赋值解构：`reactive` 对象解构或重新赋值整个对象会丢失响应式连接，而 `ref` 变量即使在函数间传递或重新给 `.value` 赋值依然保持响应式。建议基本类型优先用 `ref`。', 'ref,reactive,区别,.value,RefImpl,响应式丢失,解构赋值', '前端与全栈工程', 1, 'it-161', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (162, 'Vue 虚拟 DOM 与 Diff 算法的核心思想是什么？Vue 3 做了哪些编译优化？', '虚拟 DOM 是以 JS 对象树模拟真实 DOM 节点，通过内存中比对两次渲染的差异并批量应用真实 DOM 变更，减少高代价的重绘重排。Vue 3 引入革命性的编译时优化：1. Patch Flags（静态标记）：在编译模板时为带有动态绑定的节点标记具体类型（如仅文本变动 `1`、类名变动 `2`），Diff 时直接跳过静态节点定向比对；2. 静态节点提升（Hoist Static）：将完全不变的静态 VNode 提取到渲染函数外部只创建一次并复用；3. 快速 Diff 算法：针对同级子节点采用预处理（前置与后置相同节点排除）+ 最长递增子序列（LIS）算法，以最少移动次数完成 DOM 节点就位更新。', '虚拟DOM,Diff算法,Vue3Diff,PatchFlag,静态提升,最长递增子序列,LIS', '前端与全栈工程', 1, 'it-162', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (163, 'Vue 3 的 computed 计算属性与 watch/watchEffect 侦听器有什么区别？', '1. computed（计算属性）：基于依赖响应式数据的同步纯函数计算，具备【缓存机制】（依赖未变更时多次访问直接返回缓存结果），不应在 computed 中执行异步或修改外部状态的副作用；2. watch（显式侦听）：必须显式指定侦听源，支持获取新值 `newVal` 与旧值 `oldVal`，支持配置 `deep: true`（深度侦听）与 `immediate: true`（立即执行一次），适合执行异步操作或开销较大的业务逻辑；3. watchEffect（自动侦听）：无需指定侦听源，自动收集回调函数内部用到的所有响应式属性，组件初始化时自动立即执行一次。', 'computed,watch,watchEffect,计算属性,侦听器,缓存机制,深度侦听', '前端与全栈工程', 1, 'it-163', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (164, 'Vue 组件间通信的常用方式有哪些？各自适用于哪些父子/跨层级场景？', '1. 父传子：`props` 属性传递，子组件通过 `defineProps` 声明接收；2. 子传父：`emit` 自定义事件，子组件通过 `defineEmits` 触发父组件监听的方法；3. 双向绑定：`v-model` / `defineModel`（Vue 3.4+）；4. 跨多级爷孙组件：`provide` 与 `inject` 依赖注入，适合深层级插件或组件库共享状态；5. 全局状态管理：Pinia（替代 Vuex，轻量、无 mutations、支持 Composition API 与完善的 TypeScript）；6. 模板引用与暴露：父组件通过 `ref` 获取子组件实例，子组件通过 `defineExpose` 显式对外暴露属性与方法。', 'Vue,组件,组件通信,通信方式,常见方式,父子通信,跨层级,props,emit,provide,inject,Pinia', '前端与全栈工程', 1, 'it-164', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (165, 'React 核心机制：Virtual DOM、JSX 编译与 Reconciliation（协调）流程', '1. JSX 语法糖：通过 Babel 编译为 `React.createElement` 或 `_jsx` 函数调用，最终输出嵌套的虚拟 DOM JS 对象；2. Fiber 架构：React 16 将递归调和重构为双向链表结构的 Fiber 节点树，将漫长的不可中断渲染拆解为可被浏览器空闲时段中断和分片执行的小工作单元；3. 协调与 Commit：Render 阶段根据状态变化在内存中进行 Fiber Diff 并打上增删改 EffectTag，Commit 阶段将所有变更一次性同步应用到真实 DOM 上，保证了主线程在大规模重渲染时依然能够及时响应用户输入。', 'React核心,VirtualDOM,JSX,Fiber,Fiber架构,Reconciliation,调和流程', '前端与全栈工程', 1, 'it-165', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (166, 'React Hooks 核心原理是什么？useState 与 useEffect 的闭包陷阱如何规避？', 'Hooks 原理：在函数组件对应的 Fiber 节点上维护了一条单向链表 `memoizedState`，每次执行 Hook（如 useState/useEffect）时按固定调用顺序遍历链表获取对应状态，这也是“为什么 Hooks 绝不能写在 if 条件分支或循环内部”的根本原因。闭包陷阱产生原因：useEffect 或事件回调中捕获了旧渲染周期内的快照状态变量。规避方案：1. 规范声明依赖项数组（deps），不要遗漏依赖；2. 使用函数式更新 `setCount(prev => prev + 1)`；3. 结合 `useRef` 保存跨生命周期最新的可变引用。', 'ReactHooks,useState,useEffect,闭包陷阱,依赖项数组,useRef,Fiber链表', '前端与全栈工程', 1, 'it-166', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (167, '现代前端工程化打包构建工具对比：Vite 为什么比 Webpack 启动更快？', 'Webpack 的传统冷启动原理：无论当前页面是否需要，必须递归分析整个项目的模块依赖图，将全部代码完整打包成 Bundle 后才启动开发服务器，项目越大冷启动与热更新越慢。Vite 的革命性设计：1. 开发阶段基于浏览器原生 ES 模块（Native ESM），无需打包，按需动态请求加载当前页面的模块；2. 依赖预构建使用极速的 Go 语言编写的 esbuild，编译速度比 JS 编写的 Webpack 快 10~100 倍；3. 生产构建阶段采用 Rollup，兼顾成熟插件生态与极致代码拆分优化。', 'Vite,Webpack,构建工具,NativeESM,esbuild,Rollup,热更新,冷启动,打包速度', '前端与全栈工程', 1, 'it-167', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (168, '浏览器跨域（CORS）问题产生的原因是什么？常见的解决方案有哪些？', '跨域是由于浏览器的【同源策略（Same-Origin Policy）】引起的（协议、域名、端口三者有任意一项不一致即为跨域，浏览器会拦截带有敏感响应体数据的跨源请求）。常见解决方案：1. 后端开启 CORS（跨域资源共享）：在响应头设置 `Access-Control-Allow-Origin: *`、`Access-Control-Allow-Methods` 及 `Access-Control-Allow-Credentials`；2. 开发环境反向代理：在 Vite / Webpack 开发服务器中配置 `proxy`，利用 Node.js 中间件转发请求绕过浏览器同源限制；3. 生产环境 Nginx 反向代理：将前端静态页面和后端接口部署于同一域名下的不同路径前缀（如 `/api`）统一代理。', '跨域,CORS,同源策略,反向代理,Nginx代理,ViteProxy,预检请求,Options请求', '前端与全栈工程', 1, 'it-168', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (169, 'TypeScript 中 interface 与 type 有什么区别？泛型（Generics）的作用是什么？', '1. interface 与 type 区别：- interface 专用于定义对象形状，支持多次声明合并（Declaration Merging，适合定义库接口），支持 `extends` 继承；- type 是类型别名，功能更广泛，支持联合类型（`Union`）、元组（`Tuple`）、基本类型重命名及高级映射类型，不支持声明合并；2. 泛型（Generics）：在定义函数、接口或类时不预先指定具体类型，而是将类型作为参数在使用时动态传入，在保持类型安全与完整 IDE 语法提示的同时，实现代码的高阶通用与最大化复用。', 'TypeScript,interface,type,泛型,类型别名,声明合并,类型安全,TS', '前端与全栈工程', 1, 'it-169', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (170, '前端性能优化（Core Web Vitals）核心指标及常见优化手段有哪些？', '三大核心指标：1. LCP（最大内容绘制，衡量加载速度，应 ≤ 2.5s）：优化关键资源加载链路、SSR 服务端渲染、CDN 加速、骨架屏与关键 CSS 内联；2. INP（交互到下一次绘制，衡量交互响应度，替代 FID，应 ≤ 200ms）：拆解长任务（Long Tasks）、利用 `requestIdleCallback` 或 Web Worker 转移密集计算、避免复杂的同步渲染；3. CLS（累积布局偏移，衡量视觉稳定性，应 ≤ 0.1）：为图片和广告位显式预留宽高属性（width/height）、避免在内容上方动态插入未定高度的 DOM 元素、使用 CSS `transform` 代替宽高动画。', '前端性能优化,CoreWebVitals,CWV,LCP,INP,CLS,首屏加载,长任务,布局偏移', '前端与全栈工程', 1, 'it-170', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (171, 'Docker 容器与传统虚拟机（VM）的本质区别是什么？底层隔离原理是什么？', '传统虚拟机（VM）是通过 Hypervisor 虚拟化硬件并运行完整的 Guest OS 操作系统，每个 VM 占用数 GB 内存且启动耗时数分钟。Docker 容器并非真正的虚拟机，它直接共享宿主机的 Linux 内核，秒级启动且近乎零损耗。底层三大隔离支柱：1. Linux Namespaces（空间隔离）：隔离 pid（进程）、net（网络）、ipc（进程间通信）、mnt（文件系统挂载）、uts（主机名）；2. Cgroups（资源限制）：限制容器的 CPU 核心数、内存限额、磁盘 I/O 带宽；3. 联合文件系统（UnionFS / Overlay2）：实现镜像与容器写时复制（COW）的分层文件管理。', 'Docker容器,虚拟机,VM对比,Namespace,Cgroups,Overlay2,内核共享,容器隔离', '云原生与Linux运维', 1, 'it-171', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (172, 'Docker 镜像的分层存储机制（Overlay2 联合文件系统）是怎样的？', 'Docker 镜像是由一系列只读层（Read-Only Layer）堆叠而成的。Dockerfile 中每一条构建指令（如 `FROM`、`RUN`、`COPY`）都会生成一个独立的镜像层。当容器启动时，Docker 会在所有只读层最顶层挂载一个可写层（Container Read-Write Layer）。写时复制（Copy-on-Write）：当容器修改已有文件时，先将该文件从下方的只读层拷贝到顶层的可写层再做修改，下层保持不变。多容器共享同一份底层基础镜像层，极大节省了磁盘空间与拉取镜像带宽。', 'Docker镜像,分层存储,Overlay2,写时复制,COW,镜像层,只读层,可写层', '云原生与Linux运维', 1, 'it-172', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (173, '编写高效安全的 Dockerfile 有哪些核心最佳实践？', '关键准则：1. 选择精简基础镜像：优先采用 `alpine` 或 `distroless`（体积仅几十 MB，漏洞攻击面小）；2. 多阶段构建（Multi-Stage Builds）：在构建阶段使用完整 JDK/Node 环境编译，打包最终镜像时仅复制构建产物（如 jar/dist）到轻量运行时镜像，镜像体积可缩小 90%；3. 合并 RUN 指令并清理缓存：如 `RUN apt-get update && apt-get install -y xxx && rm -rf /var/lib/apt/lists/*`，减少无用中间层；4. 充分利用层缓存：将不常变更的依赖安装（如 `COPY package.json` ➔ `npm install`）放在业务源码拷贝之前；5. 避免使用 root 账户运行容器。', 'Dockerfile,最佳实践,多阶段构建,Alpine,镜像精简,构建缓存,容器安全', '云原生与Linux运维', 1, 'it-173', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (174, 'Docker Compose 的核心作用是什么？多容器编排与网络互通原理是怎样的？', 'Docker Compose 用于在单个宿主机上定义和运行由多个容器组成的复杂微服务应用（如一键启动 Nginx、Spring Boot、MySQL、Redis）。通过统一的 `docker-compose.yml` 声明服务依赖（`depends_on`）、端口映射、数据卷挂载及环境变量。网络原理：Docker Compose 启动时默认会为该工程创建一个独立的自定义桥接网络（Bridge Network），工程内的所有容器自动加入该网络，各容器可直接通过【服务名（Service Name）】作为域名进行内部 DNS 互相解析与通信，无需硬编码 IP。', 'DockerCompose,多容器编排,docker-compose,桥接网络,服务名通信,depends_on', '云原生与Linux运维', 1, 'it-174', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (175, 'Kubernetes（K8s）的核心架构与核心组件职责分别是什么？', 'K8s 由控制平面（Control Plane）与工作节点（Worker Node）构成：- 控制平面：1. `kube-apiserver`：集群唯一入口，暴露 REST API 供 kubectl 和内部组件交互；2. `etcd`：高可用键值存储，保存集群全量状态元数据；3. `kube-scheduler`：根据资源需求将待运行 Pod 调度到最优 Node；4. `kube-controller-manager`：运行各类控制器（如 NodeController, DeploymentController），维护集群预期状态与实际状态一致。- 工作节点：1. `kubelet`：节点核心代理，与容器运行时（CRI 如 containerd）交互管理 Pod 容器生命周期；2. `kube-proxy`：负责维护节点网络规则（iptables/IPVS），实现 Service 服务发现与负载均衡。', 'K8s,Kubernetes,核心架构,架构组件,核心组件,组件,Master节点,apiserver,etcd,kubelet', '云原生与Linux运维', 1, 'it-175', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (176, 'K8s 中 Pod、Deployment、Service 与 Ingress 的概念与关系是怎样的？', '1. Pod：K8s 中最小的部署和调度单元，包含一个或多个紧密耦合、共享网络 IP 和存储卷的容器；2. Deployment：负责管理无状态 Pod 的控制器，定义副本数量（Replicas）、声明式滚动更新（Rolling Update）与版本回滚；3. Service：Pod 的虚拟网络抽象与内网负载均衡器，由于 Pod IP 会随销毁重建而动态漂移，Service 提供固定的 ClusterIP 和 DNS 域名，利用标签选择器（Label Selector）自动路由到后端活跃的 Pod；4. Ingress：集群的外部流量七层网关入口，提供 HTTP/HTTPS 路由规则，将外部域名与请求路径转发给对应的内部 Service。', 'Pod,Deployment,Service,Ingress,K8s网络,滚动更新,服务发现,集群路由', '云原生与Linux运维', 1, 'it-176', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (177, 'K8s 中 Pod 的健康检查探针（Liveness、Readiness、Startup Probe）有何区别？', '1. Startup Probe（启动探针）：针对启动耗时较长的重型服务（如大型 Java 应用），在该探针成功之前，Liveness 和 Readiness 探针均不工作，避免服务还没启动完成就被杀死；2. Liveness Probe（存活探针）：检测容器是否处于健康运行状态，若连续失败达到阈值，kubelet 会强制杀死该容器并按重启策略重建；3. Readiness Probe（就绪探针）：检测容器是否已具备对外处理业务流量的能力，若未就绪或失败，K8s 仅将该 Pod 从对应的 Service 负载均衡端点列表（Endpoints）中剔除，暂停路由流量，但不会重启容器。', 'K8s探针,健康检查,Liveness,Readiness,Startup,存活探针,就绪探针,Endpoints', '云原生与Linux运维', 1, 'it-177', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (178, 'Linux 服务器性能排查核心四板斧：CPU、内存、磁盘 I/O、网络负载排查命令', '1. CPU 排查：`top` 查看整体负载与各进程 CPU 占用（按 P 键排序），`mpstat -P ALL 1` 查看多核使用均衡度；2. 内存排查：`free -h` 查看总物理内存、已用、缓存及 Swap 交换分区使用率；`vmstat 1` 监控虚拟内存换页与上下文切换；3. 磁盘 I/O 排查：`df -h` 检查磁盘分区容量；`iostat -xz 1` 重点观察 `%util`（磁盘忙碌百分比）与 `await`（I/O 等待时延），若 %util 接近 100% 出现高 iowait，说明遭遇云盘限速或慢 I/O 瓶颈；4. 网络排查：`netstat -nltp` 或 `ss -s` 查看连接数与端口监听；`iftop` 监控网卡瞬时流量峰值。', 'Linux性能排查,top,free,vmstat,iostat,iowait,netstat,磁盘IO,内存分析', '云原生与Linux运维', 1, 'it-178', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (179, 'Linux 常用文本处理三剑客（grep、sed、awk）核心用法与实战技巧', '1. `grep`（文本过滤）：擅长快速正则查找。如 `grep -rn "pattern" ./` 递归搜索；`grep -v` 反向排除；`grep -C 5` 显示匹配行前后上下文 5 行；2. `sed`（流编辑器）：擅长对文本做行过滤与文本替换。如 `sed -i "s/old/new/g" file.txt` 全局直接替换文件内容；`sed -n "10,20p" file.txt` 打印指定行范围；3. `awk`（文本列分析器）：擅长按列切分统计。默认以空格/制表符分列，如 `awk "{print \\$1, \\$NF}" file.txt` 打印第一列和最后一列；结合过滤与累加：`awk -F ":" "\\$3 > 1000 {sum+=\\$3} END {print sum}" /etc/passwd`。', 'grep,sed,awk,Linux三剑客,文本处理,正则搜索,文件替换,列提取', '云原生与Linux运维', 1, 'it-179', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (180, 'Nginx 常用反向代理、负载均衡策略（轮询、权重、IP Hash）与动静分离配置', '1. 反向代理：通过 `location /api/ { proxy_pass http://backend_upstream; }` 将客户端请求隐藏透明地转发至后端集群；2. 负载均衡策略（在 upstream 块中配置）：- 轮询（Round Robin，默认）：按请求时间依次分配；- 权重（`weight=n`）：按权重比例调度，性能高的机器分配更多连接；- IP Hash（`ip_hash;`）：基于客户端 IP 计算哈希路由到固定服务器，用于解决 Session 绑定；- 最少连接数（`least_conn;`）：优先调度给活跃连接最少的后端；3. 动静分离：将静态 HTML/CSS/JS/图片资源直接由 Nginx 本地读取（配合 sendfile 与 expires 缓存），动态接口请求反向代理到微服务网关。', 'Nginx,反向代理,负载均衡,upstream,轮询,权重,ip_hash,动静分离,proxy_pass', '云原生与Linux运维', 1, 'it-180', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (181, 'Nginx 高性能优化关键配置参数解析（Worker、连接数、sendfile、gzip）', '核心调优配置：1. `worker_processes auto;`：让 Nginx 启动的工作进程数与 CPU 核心数自动保持一致；2. `worker_cpu_affinity auto;`：绑定 worker 进程到具体的 CPU 核心，减少 CPU 切换开销；3. `worker_connections 65535;`：单个 worker 进程允许的最大并发连接数；4. `sendfile on;` 与 `tcp_nopush on;`：开启内核零拷贝传输文件，极大降低磁盘读取与网络传输上下文切换；5. `keepalive_timeout 65;`：长连接超时时间；6. `gzip on;`：开启 Gzip 压缩（配置 `gzip_types` 与 `gzip_comp_level 5`），文本资源传输体积通常可压缩 70% 以上。', 'Nginx,高性能,调优,高性能调优,核心配置,优化配置,worker_processes,sendfile,gzip', '云原生与Linux运维', 1, 'it-181', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (182, 'CI/CD 持续集成与持续部署流水线的核心阶段与自动化实践是怎样的？', 'CI/CD 实现了从代码推送到线上运行的自动化流水线闭环：1. 持续集成（CI）：代码提交（Push / PR）触发自动化代码静态检查（SonarQube/Checkstyle）、单元测试执行并生成测试覆盖率报告、编译打包（Maven package / npm run build），若任意一步报错立即打断流水线并邮件通知提交者；2. 持续交付/部署（CD）：通过 Dockerfile 自动化构建服务镜像并推送到容器镜像仓库（Harbor/阿里云ACR），接着通过 Helm / kubectl / SSH 触发目标环境（测试/预发/生产）的滚动更新与冒烟自动化验证，实现低风险、高频次、标准化的敏捷交付。', 'CICD,持续集成,持续部署,GitHubActions,Jenkins,自动化流水线,自动化构建,滚动发布', '云原生与Linux运维', 1, 'it-182', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (183, 'TCP 三次握手与四次挥手的详细流程是怎样的？为什么挥手需要等待 2MSL？', '1. 三次握手：客户端发送 SYN(seq=x) ➔ 服务端收到并回复 SYN+ACK(seq=y, ack=x+1) ➔ 客户端回复 ACK(ack=y+1)，双方确认彼此收发能力正常并同步初始序列号；2. 四次挥手：客户端发送 FIN ➔ 服务端回复 ACK（此时进入半关闭状态，服务端可能仍有数据待发送） ➔ 服务端发送完毕后发送 FIN ➔ 客户端回复 ACK 并进入 TIME_WAIT 状态；3. 为什么等待 2MSL（Maximum Segment Lifetime，报文最大生存时间）：① 保证客户端发送的最后一个 ACK 报文能够顺利到达服务端，若丢包服务端重发 FIN，客户端在 2MSL 内可重新发送 ACK；② 确保本次连接产生的所有网络残留报文在网络中彻底消亡，防止“迷途报文”干扰后续新建立的连接。', 'TCP三次握手,四次挥手,2MSL,TIME_WAIT,SYN,ACK,FIN,序列号,网络协议', '计算机网络与安全', 1, 'it-183', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (184, 'TCP 与 UDP 协议的核心区别是什么？各自适用于哪些业务场景？', '1. 连接性：TCP 是面向连接的可靠流式传输协议；UDP 是无连接的面向报文传输协议；2. 可靠性：TCP 通过确认应答、超时重传、流量控制和拥塞控制保证数据无差错、不丢失、不重复且按序到达；UDP 不保证可靠交付，只管尽最大努力发送；3. 开销与速度：TCP 首部最小 20 字节，传输开销大速度相对慢；UDP 首部仅 8 字节，开销极小且速度极快；4. 适用场景：TCP 适用于对数据准确性要求极高的场景（HTTP/HTTPS 网页、文件传输 FTP、邮件 SMTP、金融交易）；UDP 适用于对实时性要求高但容忍少量丢包的场景（音视频通话、实时流媒体、在线竞技游戏、DNS 解析）。', 'TCP,UDP,协议区别,网络传输,适用场景,实时通信,三次握手', '计算机网络与安全', 1, 'it-184', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (185, 'TCP 是如何实现可靠传输的？（确认应答、超时重传、流量控制、拥塞控制）', '五大核心保障机制：1. 序列号与确认应答（ACK）：发送方为每个字节分配序列号，接收方通过 ACK 号告知下一次期望接收的字节编号；2. 超时重传（RTO）：发送方发出报文后启动定时器，超时未收到 ACK 则重新发送；3. 滑动窗口（Sliding Window）：无需每发一个包都等待确认，允许连续发送窗口大小内的数据，极大提高吞吐量；4. 流量控制（Flow Control）：接收方在 ACK 报文中携带通告窗口（rwnd）大小，防止发送方发送过快导致接收缓冲区溢出；5. 拥塞控制（Congestion Control）：通过慢启动、拥塞避免、快重传与快恢复动态调整拥塞窗口（cwnd），防止网络链路发生堵塞瘫痪。', 'TCP,可靠传输,传输可靠,超时重传,滑动窗口,流量控制,拥塞控制,ACK应答,慢启动', '计算机网络与安全', 1, 'it-185', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (186, 'HTTP 协议版本演进：HTTP 1.0、HTTP 1.1、HTTP 2.0、HTTP 3.0 的核心改进', '1. HTTP 1.0：短连接，每次请求都需要重新建立 TCP 连接；2. HTTP 1.1：引入长连接（`Keep-Alive` 默认复用 TCP）、管道化（Pipelining）、Host 请求头支持虚拟主机、Chunked 动态分块传输，但仍存在【队头阻塞（HOL）】问题；3. HTTP 2.0：基于二进制分帧层（Binary Framing），支持【多路复用（Multiplexing）】（单连接并发多个请求彻底消除 HTTP 队头阻塞）、头部压缩（HPACK 算法）、服务端推送（Server Push）；4. HTTP 3.0：彻底摒弃 TCP，改用基于 UDP 的 `QUIC` 协议，在传输层彻底解决了 TCP 的队头阻塞问题，并实现 0-RTT 极速建联与连接迁移。', 'HTTP版本,HTTP1.1,HTTP2,HTTP3,QUIC,多路复用,队头阻塞,Keep-Alive,二进制分帧', '计算机网络与安全', 1, 'it-186', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (187, 'HTTPS 的工作原理是什么？TLS/SSL 对称加密与非对称加密握手流程', 'HTTPS = HTTP + TLS/SSL 加密协议。核心流程（混合加密机制）：1. 客户端发起 `Client Hello`，发送支持的 TLS 版本和随机数 R1；2. 服务端回复 `Server Hello`，发送选定的加密套件、数字证书（包含公钥）和随机数 R2；3. 客户端验证证书合法性（通过操作系统内置 CA 根证书链校验防伪签名）；4. 验证通过后，客户端生成第三个随机数（Pre-Master Secret），用服务端的【非对称公钥】加密后发送给服务端；5. 服务端用自己的【非对称私钥】解密得到 Pre-Master Secret；6. 双方结合 R1 + R2 + Pre-Master 生成完全一致的【对称加密主密钥】；7. 后续的所有 HTTP 业务数据传输全部使用该对称密钥进行高速加密通信。', 'HTTPS,TLS,SSL握手,CA证书,数字签名,混合加密,协商密钥,对称通信', '计算机网络与安全', 1, 'it-187', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (188, 'HTTP 状态码常见分类与高频状态码解析（200, 301, 302, 400, 401, 403, 404, 500, 502, 504）', '分类：1xx 信息提示、2xx 成功、3xx 重定向、4xx 客户端错误、5xx 服务端错误。高频解析：- 200 OK：请求成功并返回内容；204 No Content：请求成功但无响应体；- 301 Moved Permanently：永久重定向（浏览器会强制缓存新 URL）；302 Found：临时重定向；304 Not Modified：协商缓存命中直接使用本地缓存；- 400 Bad Request：请求参数不合法；401 Unauthorized：未提供有效认证凭证（未登录）；403 Forbidden：已通过身份验证但没有访问权限；404 Not Found：找不到请求的资源路由；- 500 Internal Error：后端服务器代码发生未捕获异常；502 Bad Gateway：网关或 Nginx 无法连通后端微服务；504 Gateway Timeout：网关等待后端服务响应超时。', 'HTTP状态码,301,302,304,401,403,404,500,502,504,重定向,网关超时', '计算机网络与安全', 1, 'it-188', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (189, 'Session、Cookie、Token 与 JWT 认证鉴权方案的区别与选型', '1. Cookie：存储在浏览器本地的小文本（≤4KB），每次请求随请求头自动携带，易受 CSRF 攻击；2. Session：用户会话状态保存在服务端内存中，客户端仅持有 SessionID，缺点在于分布式多节点集群下需要做 Session 共享同步，水平扩容受限；3. Token：通用的令牌鉴权概念，由服务端下发并由客户端显式存放在 Storage 中在 Header 中手动携带；4. JWT（JSON Web Token）：去中心化无状态令牌，将用户 UID、角色权限及过期时间等载荷直接加密签名写入 Token 自身，服务端只需使用密钥进行验签计算即可完成身份校验，无需查询 Redis 或数据库，非常契合大规模微服务架构。', 'Session,Cookie,Token,JWT,认证鉴权,单点登录,分布式Session,区别选型', '计算机网络与安全', 1, 'it-189', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (190, 'JWT（JSON Web Token）的内部结构是怎样的？无状态 JWT 如何实现主动登出失效？', 'JWT 结构由点号 `.` 分隔的三段组成：`Header.Payload.Signature`。1. Header：说明令牌类型（JWT）与签名算法（如 HS256/RS256）；2. Payload：载荷信息（如 sub 业务主键、exp 过期时间戳、自定义用户信息），采用 Base64URL 编码（注意：明文可见，不可存放密码等敏感信息！）；3. Signature：数字签名，由 `HMACSHA256(Base64(Header) + "." + Base64(Payload), secret)` 计算得出，防篡改。无状态失效方案：因为 JWT 一旦签发在过期前天然有效，主动登出时可在 Redis 中维护一个【黑名单（Blacklist）】，将注销的 Token 存入 Redis 并设置与其剩余 TTL 一致的过期时间，网关鉴权时先查黑名单拦截。', 'JWT,内部结构,Token结构,主动注销,主动登出,JWT黑名单,注销,Payload,Signature', '计算机网络与安全', 1, 'it-190', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (191, '常见 Web 安全漏洞与防御手段：SQL 注入、XSS 跨站脚本、CSRF 跨站请求伪造', '1. SQL 注入：黑客通过构造恶意输入拼接 SQL 指令窃取或破坏数据库。防御：使用参数化查询（PreparedStatement，MyBatis 使用 `#{}` 严格参数绑定，禁止使用 `${}` 拼接）；2. XSS（跨站脚本攻击）：黑客向页面注入恶意 JS 代码并在其他用户浏览器执行以盗取 Cookie。防御：对所有用户输入输出进行 HTML 实体转义编码、设置 Cookie 的 `HttpOnly` 属性禁止 JS 读取、配置 CSP 内容安全策略；3. CSRF（跨站请求伪造）：黑客诱导用户点击第三方恶意链接并利用用户已有 Cookie 伪造合法请求。防御：采用 SameSite Cookie 策略、敏感接口使用 JWT 替换 Cookie、关键操作加入随机 Anti-CSRF Token 验证。', 'Web安全,SQL注入,XSS,CSRF,参数化查询,HttpOnly,SameSite,安全防御', '计算机网络与安全', 1, 'it-191', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (192, '对称加密算法（AES）与非对称加密算法（RSA/ECC）的原理与应用场景', '1. 对称加密（如 AES-256、DES）：加密和解密使用【同一套密钥】。优点：计算速度极快，CPU 损耗小，适合对海量业务数据、文件流或大文本进行加密存储与传输；缺点：密钥分发困难，若密钥泄露则全局失守；2. 非对称加密（如 RSA-2048、ECC 椭圆曲线）：拥有配对的【公钥】与【私钥】，公钥对外公开用于加密或验签，私钥严格保密用于解密或数字签名。优点：安全性极高，无需提前共享私钥；缺点：算法涉及大数质因数分解或离散对数计算，速度比对称加密慢数千倍，通常仅用于身份验签及在握手阶段协商对称会话密钥。', '对称加密,非对称加密,加密算法,加密区别,区别,AES,RSA,ECC,密钥协商,数据加密', '计算机网络与安全', 1, 'it-192', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (193, '常见时间复杂度与空间复杂度分析（大 O 表示法）核心规则是怎样的？', '大 O 表示法用于衡量算法随着输入规模 n 增长时的执行时间与资源消耗趋势。常见阶层由快到慢为：`O(1) 常数阶` < `O(log n) 对数阶`（二分查找） < `O(n) 线性阶`（单层循环） < `O(n log n) 线性对数阶`（快排、归并） < `O(n²) 平方阶`（双重冒泡） < `O(2^n) 指数阶` < `O(n!) 阶乘阶`。化简法则：1. 只保留最高阶项，忽略低阶项；2. 省略最高阶项前面的常数系数；3. 空间复杂度是指算法在运行过程中临时占用存储空间的大小趋势，递归调用栈深度亦属于空间消耗。', '时间复杂度,空间复杂度,大O表示法,算法分析,对数阶,线性阶,复杂度计算', '数据结构与算法', 1, 'it-193', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (194, '数组（Array）与链表（LinkedList）在内存分配与操作性能上的核心区别是什么？', '1. 内存分配：数组要求分配一块连续的物理内存空间；链表采用分散的离散节点，节点之间通过 next/prev 指针相连，内存利用更灵活且无固定大小限制；2. 随机访问（Read）：数组具备寻址公式 `address = base + index * size`，支持 O(1) 毫秒级随机访问；链表必须从头节点顺序向后遍历查找，时间复杂度为 O(n)；3. 插入与删除（Write）：数组在指定位置增删需要移动其后所有元素，平均时间复杂度为 O(n)；链表若已定位到目标节点，修改指针引用即可完成增删，时间复杂度为 O(1)；4. 缓存命中：数组在物理连续内存上有极高的 CPU 缓存行（Cache Line）局部性命中率。', '数组,链表,Array,LinkedList,区别,随机访问,内存连续,指针,增删性能', '数据结构与算法', 1, 'it-194', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (195, '哈希表（Hash Table）解决哈希冲突的常见方法有哪些？（链地址法与开放寻址法）', '当两个不同 Key 计算出相同的哈希槽位时产生哈希冲突。两大经典解法：1. 链地址法（Separate Chaining，拉链法）：每个哈希槽位保存一个链表头指针，所有冲突的元素以链表节点形式挂在对应槽位后面（Java HashMap 采用此方案，并在链表过长时升级为红黑树）；2. 开放寻址法（Open Addressing）：所有元素都保存在数组中，冲突时按某种探测策略寻找下一个未被占用的空槽位：- 线性探测（Linear Probing）：冲突后依次向后检查 `i+1, i+2...`；- 二次探测：按平方步长 `i+1², i-1²...` 检查；- 双重哈希：使用第二个哈希函数重新计算步长。', '哈希冲突,哈希表,链地址法,拉链法,开放寻址法,线性探测,二次探测', '数据结构与算法', 1, 'it-195', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (196, '二叉树（Binary Tree）的三种深度遍历方式（前序、中序、后序）与层序遍历原理', '1. 前序遍历（Pre-order）：根节点 ➔ 左子树 ➔ 右子树，常用于树的复制与序列化；2. 中序遍历（In-order）：左子树 ➔ 根节点 ➔ 右子树，对于二叉搜索树（BST），中序遍历的结果严格单调递增；3. 后序遍历（Post-order）：左子树 ➔ 右子树 ➔ 根节点，常用于子节点计算与树的自底向上清理（如计算目录占用空间）；4. 层序遍历（Level-order，广度优先 BFS）：从根节点开始自顶向下、自左向右逐层访问，底层通常借助【队列（Queue）】先进先出特性实现。', '二叉树,前序,中序,后序,层序,层序遍历,二叉树遍历,前序遍历,中序遍历,后序遍历,BFS', '数据结构与算法', 1, 'it-196', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (197, '二叉搜索树（BST）、平衡二叉树（AVL）与红黑树（Red-Black Tree）的演进与平衡机制', '1. 二叉搜索树（BST）：左子树所有节点均小于根，右子树所有节点均大于根。若插入连续升序数据会退化成单向链表，查找复杂度从 O(log n) 恶化至 O(n)；2. AVL 树：严格平衡二叉树，任意节点左右子树高度差（平衡因子）不超过 1，查询极快，但每次插入删除频繁触发旋转（LL/RR/LR/RL），写开销大；3. 红黑树：弱平衡二叉树，通过 5 大红黑规则（根黑、叶黑、红子必黑、任意节点至叶子黑高相同）保证【最长路径不超过最短路径的 2 倍】，在插入删除更新（最多 3 次旋转）与查询效率之间取得了最出色的工程权衡。', '二叉搜索树,BST,平衡二叉树,AVL树,红黑树,树旋转,黑高,平衡机制', '数据结构与算法', 1, 'it-197', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (198, '快速排序（Quick Sort）与归并排序（Merge Sort）的核心思想与时间复杂度对比', '两者均基于分治思想（Divide and Conquer）：1. 快速排序：挑选一个基准值（Pivot），通过双指针分区使得左边元素小于基准、右边大于基准，然后递归处理左右两部分。平均时间复杂度 O(n log n)，最好 O(n log n)，最坏退化为 O(n²)（可通过随机三数取中规避），为原地排序（In-place，空间 O(log n)），是非稳定排序；2. 归并排序：将数组不断对半拆分为左右两半递归排序，最后通过双指针将两个有序子数组合并为一个有序数组。时间复杂度始终稳定为 O(n log n)，但需要额外 O(n) 辅助临时数组，是稳定排序。', '快速排序,归并排序,快排,分治法,时间复杂度,稳定排序,双指针,Pivot', '数据结构与算法', 1, 'it-198', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (199, '二分查找（Binary Search）的实现边界细节与在旋转有序数组中的应用', '标准二分实现核心边界：`int mid = left + (right - left) / 2`（防止整数加法溢出），循环条件为 `while (left <= right)`。在【旋转有序数组（如 [4,5,6,7,0,1,2]）】中查找目标值时，关键在于判断哪一半必然保持单调有序：每次计算 mid 后，若 `nums[left] <= nums[mid]`，说明前半部分绝对升序，检查 target 是否落在 `[nums[left], nums[mid])` 区间内；若在则收缩 `right = mid - 1`，否则在后半部分查找；反之说明后半部分绝对升序，同理比对收缩，时间复杂度依然保持 O(log n)。', '二分查找,BinarySearch,旋转有序数组,边界条件,整数溢出,对数时间', '数据结构与算法', 1, 'it-199', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (200, 'LRU（最近最少使用）缓存淘汰算法的实现原理是什么？如何基于哈希表与双向链表构建？', 'LRU 核心要求 `get` 与 `put` 操作均在 O(1) 时间复杂度内完成。底层数据结构为【哈希表（HashMap）+ 双向链表（Doubly Linked List）】：1. 双向链表按时间先后顺序串联数据节点，头部为最近访问节点，尾部为最久未访问节点；2. 哈希表的 Key 存储业务键，Value 直接存储指向链表中对应 Node 节点的引用指针；3. `get(key)`：在 HashMap 找到节点并将其摘下移到双向链表头部，返回值；4. `put(key, val)`：若已存在则更新值并移至链表头部；若不存在且容量已满，则将链表尾部（最久未使用）节点删除并在 HashMap 中同步移除，然后将新节点插入链表头部。', 'LRU,最近最少使用,缓存淘汰,双向链表,哈希表,O(1)复杂度,算法设计', '数据结构与算法', 1, 'it-200', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (201, '动态规划（Dynamic Programming）的核心解题步骤是怎样的？如何寻找状态转移方程？', '动态规划适用于具有【最优子结构】和【重叠子问题】的优化极值问题。标准解题四步法：1. 明确状态定义：明确数组 `dp[i]` 或 `dp[i][j]` 所代表的物理意义（如到达第 i 阶台阶的方案数、前 i 个物品容量为 j 的最大价值）；2. 寻找状态转移方程：推导 `dp[i]` 如何由规模更小的子问题（如 `dp[i-1]`、`dp[i-2]`）归纳计算得出；3. 确定边界条件与初始化：设定 `dp[0]`、`dp[1]` 的基础真值，防止越界；4. 确定遍历顺序并考虑空间压缩：自底向上循环计算，若只依赖前一项状态可利用滚动变量将 O(n) 空间优化为 O(1)。', '动态规划,DP,状态转移方程,最优子结构,重叠子问题,空间压缩,滚动数组', '数据结构与算法', 1, 'it-201', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (202, '深度优先搜索（DFS）与广度优先搜索（BFS）的算法思想与适用场景对比', '1. DFS（深度优先搜索）：基于“不撞南墙不回头”思想，沿着一条路径一直递归到底部，再回溯尝试其他分支。底层通过【函数递归调用栈】实现。空间复杂度取决于树的深度 O(h)。适用于全排列枚举、图的连通性分析、拓扑排序、数独与路径搜索；2. BFS（广度优先搜索）：基于“波纹扩散”思想，以当前节点为中心逐层向外平铺展开遍历。底层通过【队列（Queue）】先进先出实现。空间复杂度取决于单层最大宽度 O(w)。核心绝技在于：在无权图或等权图中能够天然保证【第一次访问到目标节点即为最短路径】。', 'DFS,BFS,深度优先搜索,广度优先搜索,回溯,最短路径,队列,递归栈', '数据结构与算法', 1, 'it-202', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (203, '大语言模型（LLM）底层核心架构 Transformer 与自注意力机制（Self-Attention）原理', '主流大模型（如 GPT、Gemini、Llama）均基于 Transformer 架构。核心灵魂是自注意力机制（Self-Attention）：将输入的每个 Token 映射为 Query（Q 查询）、Key（K 键）、Value（V 值）三个向量，通过点积注意力公式 `Attention(Q, K, V) = softmax((Q * K^T) / sqrt(d_k)) * V` 计算当前词与上下文中所有其他词的相关性权重得分。多头注意力（Multi-Head Attention）进一步让模型在不同投影子空间中同时关注不同层次的语义特征（如句法、代词指代、长程逻辑依赖），彻底突破了传统 RNN 无法并行训练与长文本遗忘的瓶颈。', 'Transformer,自注意力机制,SelfAttention,大模型架构,QKV,多头注意力,LLM', '人工智能与大模型', 1, 'it-203', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (204, '什么是大模型的 RAG（检索增强生成）？核心架构与向量数据库（Vector DB）的作用', 'RAG（Retrieval-Augmented Generation）解决了大模型知识时效性滞后、私有域数据缺失及“胡说八道（幻觉）”的痛点。核心三步流：1. 检索（Retrieval）：将用户提问转换为嵌入向量，在向量数据库（如 Milvus, Pinecone, Chroma）中利用余弦相似度或 HNSW 索引检索出最相关的 Top-K 私域文档切片；2. 增强（Augmentation）：将检索到的事实文档作为参考上下文（Context）动态拼装到 Prompt 提示词中；3. 生成（Generation）：引导大模型基于提供的上下文事实进行精准生成和引用回答。向量数据库负责在千万级高维向量空间内毫秒级完成近邻检索。', 'RAG,检索增强生成,向量数据库,VectorDB,私域知识库,TopK检索,提示词增强', '人工智能与大模型', 1, 'it-204', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (205, '文本向量化嵌入（Text Embedding）的原理是什么？余弦相似度如何计算？', 'Embedding 是将离散的高维自然语言文本（单词、句子或段落）映射为一个固定维度的低维连续稠密浮点数向量（如 768 或 1536 维空间坐标）。在嵌入空间中，语义越相近的文本，其几何向量距离越靠近。余弦相似度（Cosine Similarity）通过计算两个向量夹角的余弦值评估语义相关度：`cos(θ) = (A · B) / (||A|| * ||B||)`，取值范围在 -1 到 1 之间（在非负文本嵌入中通常在 0 到 1），值为 1 表示完全同向相关，0 表示正交无关联。', 'Embedding,文本嵌入,向量化,余弦相似度,语义搜索,高维向量,点积', '人工智能与大模型', 1, 'it-205', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (206, '大模型微调（Fine-Tuning）与提示工程（Prompt Engineering）的区别与选型策略', '1. Prompt 工程：不修改任何底层模型权重，仅通过精心设计指令、提供 Few-Shot 示例或构建 CoT 思维链引导模型输出。优点：零门槛、零算力成本、秒级迭代；缺点：受限于上下文窗口长度，难以注入海量专有垂直领域事实知识；2. 模型微调（Fine-Tuning）：在预训练大模型基础上输入标注好的特定领域问答数据集，更新部分或全部模型权重。优点：深度内化特定专业术语、行业规范格式与专属风格；缺点：算力昂贵、易发生灾难性遗忘。工业界黄金组合：【RAG 负责提供事实底料 + 提示工程规范输出 + 轻量微调定制输出风格】。', '大模型,微调,Prompt,提示工程,提示词工程,FineTuning,模型微调,选型策略', '人工智能与大模型', 1, 'it-206', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (207, '参数高效微调技术 LoRA（Low-Rank Adaptation）的核心数学原理与工程优势', '全量微调参数规模巨大（如 70B 模型微调需要数张 80GB A100/H100 显卡）。LoRA 核心思想：冻结大模型原本的预训练稠密权重矩阵 $W_0 \\in \\mathbb{R}^{d 	imes k}$，在旁边旁路增加两个低秩分解矩阵 $A \\in \\mathbb{R}^{r 	imes k}$ 和 $B \\in \\mathbb{R}^{d 	imes r}$（其中秩 $r \\ll \\min(d, k)$，通常取 8 或 16），前向传播计算为 $W = W_0 + rac{lpha}{r} (B \\cdot A)$。训练时仅更新旁路的小矩阵 $A$ 与 $B$，可训练参数量骤降至原模型的 1% 以下，显存占用降低 70%，且同一底座大模型可灵活拔插挂载多个不同业务方向的 LoRA 权重文件。', 'LoRA,低秩微调,低秩适配,省显存,显存优化,PEFT,高效微调,参数冻结', '人工智能与大模型', 1, 'it-207', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (208, '什么是 AI Agent（智能体）？核心四大要素（规划、记忆、工具、行动）是怎样的？', 'AI Agent 是以大语言模型为大脑核心、具备自主感知环境、推理规划并自主调用外部工具达成复杂目标的智能实体。核心四大架构支柱：1. 目标规划（Planning）：任务分解（将大目标拆解为子步骤链如 ReAct / Reflexion）与自我反思（对执行结果复盘修正）；2. 记忆系统（Memory）：短期记忆（当前对话上下文窗口）与长期记忆（通过向量库存储历史经验）；3. 工具调用（Tools）：利用 Function Calling 调用外部搜索、数据库查询、运行代码与执行 API；4. 行动执行（Action）：根据规划调用工具并将外部反馈重新灌入模型进行下一步推演。', 'AIAgent,智能体,规划,记忆,工具调用,FunctionCalling,ReAct框架,智能体架构', '人工智能与大模型', 1, 'it-208', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (209, '大模型生成控制参数解析：Temperature、Top_p、Top_k 分别控制什么？如何科学调参？', '1. Temperature（温度值，0~2）：控制输出概率分布的平滑度。值越低（如 0.1~0.3），模型越保守确定，生成答案越严谨精确（适合写代码、数学推理、提取数据）；值越高（如 0.8~1.2），低概率词越有机会被选中，回答越具创造性和发散性（适合诗歌、小说创作）；2. Top_p（核采样，0~1）：按词表中词的概率降序排列，仅在累积概率达到 p 的候选词集中采样；3. Top_k（候选词数）：仅在概率最高的前 k 个词中挑选。调参法则：一般建议固定 Top_p 为 0.9，仅微调 Temperature 即可达到理想效果。', 'Temperature,Top_p,Top_k,采样参数,模型生成,调参技巧,随机性,确定性', '人工智能与大模型', 1, 'it-209', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (210, '如何解决大语言模型“幻觉（Hallucination）”问题？工业落地有哪些约束手段？', '幻觉是指大模型一本正经地捏造不存在的事实或推导错误。工业界五重防御手段：1. RAG 检索增强：强制模型根据私域真实文档回答，并在 Prompt 中严厉声明“若文档中未提及请回答不知道，禁止臆测”；2. 约束输出格式：通过 Structured Outputs / JSON Schema 强制模型按既定结构输出字段，杜绝散漫发挥；3. Few-Shot 优质示例引导：提供真实准确的正反示例约束推演逻辑；4. 降低 Temperature（如设为 0~0.2）：极大收敛随机采样；5. 双智能体对抗审核（Guardrails）：引入专门的 Critic 评审智能体，对照原始事实材料对初版答案进行事实验证和打分过滤。', '大模型,幻觉,大模型幻觉,解决幻觉,幻觉问题,防幻觉,Hallucination,RAG约束', '人工智能与大模型', 1, 'it-210', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (211, '大模型长上下文处理机制与思维链（CoT, Chain of Thought）提示词技巧实践', '1. 长上下文技术：传统的 RoPE 旋转位置编码在超过训练长度时性能退化，现代模型通过位置外推（NTK-aware Scaling、YaRN）与高效注意力机制扩展至 100K~1M Token，但必须警惕“迷失在中间（Lost in the Middle）”现象，关键指令应放在 Prompt 的开头与结尾；2. 思维链（Chain of Thought）：在复杂数学计算、逻辑推演和代码分析场景中，不要求模型直接给出最终答案，而是通过提示词“请一步步思考（Let''s think step by step）”引导模型显式输出中间推理过程，从而极大提高复杂逻辑推理的正确率。', '思维链,CoT,长上下文,RoPE,提示词技巧,一步步思考,逻辑推理', '人工智能与大模型', 1, 'it-211', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (212, 'AI 大模型在智能在线教育场景（代码审查、个性化导学、学情诊断）中的落地架构', '在线教育平台标准 AI 智能体应用架构：1. 学情诊断 Agent：收集学员的答题正答率、视频观看驻留时段、随堂笔记打点，构建多维学员能力画像；2. 自动化代码审查 Agent（Code Reviewer）：在学员提交实验作业后，通过 AST 语法树解析与大模型双重结合，对代码结构、算法复杂度、阿里巴巴代码规范及潜在 NPE 进行逐行代码批注；3. 专属 AI 答疑导师：结合课程配套教案与课件源码作为 RAG 知识库，根据学员当前学习的视频时间戳精准答疑，秒级生成排查思路与指导用例。', '大模型,在线教育,教育场景,落地,落地架构,导学,智能导学,学情诊断,CodeReview,教学智能体', '人工智能与大模型', 1, 'it-212', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (213, '面向对象设计的 SOLID 五大原则是什么？在软件工程中如何落地实践？', 'SOLID 原则是面向对象设计与可维护代码的黄金基石：1. S - 单一职责原则（Single Responsibility）：一个类应该只有一个引起它变化的原因，避免臃肿的“上帝类”；2. O - 开闭原则（Open-Closed）：对扩展开放，对修改关闭。通过接口和抽象类扩展新功能，禁止修改原有测试通过的底层源码；3. L - 里氏替换原则（Liskov Substitution）：子类必须能够无缝替换其基类且不会破坏程序正确性，子类不应覆盖父类的非抽象已实现方法；4. I - 接口隔离原则（Interface Segregation）：客户端不应被强迫依赖它不需要的胖接口，应将大接口拆分为细粒度小接口；5. D - 依赖倒置原则（Dependency Inversion）：高层模块不应依赖低层模块，二者都应依赖抽象接口，面向接口编程。', 'SOLID原则,单一职责,开闭原则,里氏替换,接口隔离,依赖倒置,面向对象设计', '系统架构与设计模式', 1, 'it-213', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (214, '常见创建型设计模式：单例模式（双重检查锁定 DCL）与工厂模式的实现与实战', '1. 单例模式（Singleton）：确保一个类仅有一个实例并提供全局访问点。双重检查锁定（DCL）标准实现：`private volatile static Singleton instance;`（必须加 `volatile` 禁止指令重排，防止多线程获取到尚未完成初始化的半成品对象！），进入方法先判空，加 synchronized 锁，锁内再判空，最后创建实例；2. 简单工厂 vs 工厂方法 vs 抽象工厂：简单工厂由单一工厂类根据类型参数创建对象（违背开闭原则）；工厂方法为每个产品定义独立工厂子类（符合开闭原则）；抽象工厂提供创建一系列相关或相互依赖的产品族接口，隐藏具体产品实现。', '单例模式,DCL,双重检查锁定,volatile,工厂模式,抽象工厂,设计模式,创建型模式', '系统架构与设计模式', 1, 'it-214', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (215, '常见结构型与行为型设计模式：策略模式、责任链模式与观察者模式的实战应用', '1. 策略模式（Strategy）：定义一系列算法族并封装起来使它们可以相互替换，避免庞大恶心的 `if-else` 或 `switch` 分支（如支付渠道选择微信/支付宝/银联，结合 Spring Map 依赖注入实现秒级优雅路由）；2. 责任链模式（Chain of Responsibility）：将多个处理器连成链式结构，请求沿链依次传递直到有对象处理它（如 Netty ChannelPipeline、Spring Cloud Gateway 过滤器链、敏感词审核流）；3. 观察者模式（Observer）：一对多依赖关系，主题状态改变时自动通知所有订阅者（如 Spring ApplicationEvent 事件驱动、消息发布订阅）。', '策略模式,责任链模式,观察者模式,设计模式,if-else重构,过滤器链,事件驱动', '系统架构与设计模式', 1, 'it-215', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (216, '分布式系统 CAP 定理与 BASE 理论的核心内涵是什么？AP 与 CP 如何权衡选型？', '1. CAP 定理：在分布式系统中，一致性（Consistency 强一致）、可用性（Availability 每次请求都能获得非错响应）、分区容错性（Partition tolerance 允许网络丢包或分区）三者不可兼得。由于网络分区在分布式环境下必然存在，P 必须保证，架构师只能在 CP 与 AP 之间权衡：- CP 系统（如 ZooKeeper, etcd, HBase）：网络分区发生时宁愿拒绝服务也要保证数据绝对一致；- AP 系统（如 Eureka, Cassandra）：发生分区时优先保障系统可用性，牺牲强一致性；2. BASE 理论：基于 AP 权衡总结出的实践指南——基本可用（Basically Available）、软状态（Soft state）、最终一致性（Eventual consistency），广泛应用于电商微服务系统。', 'CAP定理,BASE理论,分布式理论,强一致性,最终一致性,AP模式,CP模式,分区容错', '系统架构与设计模式', 1, 'it-216', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (217, '分布式事务常见解决方案对比：2PC、TCC 补偿型、本地消息表与 Seata AT 模式', '1. 2PC（两阶段提交）：准备阶段投票与提交阶段执行，强一致性，但存在同步阻塞、单点故障与数据不一致风险；2. TCC（Try-Confirm-Cancel）：业务层两阶段，Try 预留资源、Confirm 真正执行、Cancel 释放资源，性能高，但业务代码侵入极重，必须保证各操作的幂等与防悬挂；3. 本地消息表：业务数据与发送消息在同一个本地数据库事务内落库，通过定时任务或 Canal 读取重试发送 MQ，下游成功后回调修改状态，实现最终一致性；4. Seata AT 模式：阿里开源低侵入方案，基于两阶段提交，自动解析 SQL 生成前镜像（Before-Image）和后镜像（After-Image），一阶段提交本地事务释放锁，二阶段异步清理镜像或自动反向补偿生成反向回滚 SQL。', '分布式事务,2PC,TCC,本地消息表,Seata,SeataAT,最终一致性,两阶段提交', '系统架构与设计模式', 1, 'it-217', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (218, '分布式全局唯一 ID 生成方案对比：UUID、数据库自增、Redis 自增与雪花算法（Snowflake）', '1. UUID：本地生成无网络开销，但为 36 位无序字符串，作为 MySQL 聚簇索引主键会导致严重的 B+ 树叶子节点分裂与磁盘 I/O 碎片；2. 数据库自增主键 / 号段模式：生成严格递增数值，但依赖单点数据库写并发瓶颈，分库分表下需维护步长容易冲突；3. Redis `INCR`：单线程原子递增，性能高，但需要考虑持久化与 Redis 集群维护开销；4. 雪花算法（Snowflake，推荐）：64 位 Long 型整数，由 1 位符号位 + 41 位时间戳（可用69年） + 10 位工作机器 ID（5位数据中心+5位机器节点） + 12 位序列号（单节点每毫秒并发生成 4096 个 ID）构成，趋势递增、不依赖网络极速本地生成，需注意防范服务器 NTP 时钟回拨问题。', '分布式ID,全局唯一ID,雪花算法,Snowflake,UUID,自增ID,时钟回拨,主键设计', '系统架构与设计模式', 1, 'it-218', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (219, '高并发高可用系统架构设计的三大法宝：缓存、限流、降级的核心实践与原则', '1. 缓存（Cache）：将高频热点只读数据推向离用户最近的节点（浏览器强缓存 ➔ CDN 节点 ➔ Nginx 本地缓存 ➔ Redis 分布式缓存 ➔ JVM 内存），读性能提升数百倍；2. 限流（Rate Limiting）：当突发流量超过系统设计容量时，主动抛弃超出阈值的请求以保护核心服务不宕机。常见算法包括计数器、滑动时间窗口、漏桶算法（固定速率输出）与令牌桶算法（允许突发流量，如 Guava RateLimiter）；3. 降级（Fallback）：系统面临高压负载时，暂时关闭非核心次要功能（如降级评价、关闭智能推荐、简化展示为静态内容），释放 CPU 与数据库连接算力，优先保证核心交易链路 100% 顺畅。', '高并发架构,三板斧,缓存,限流,降级,令牌桶,漏桶算法,服务防护', '系统架构与设计模式', 1, 'it-219', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (220, '微服务架构下服务雪崩效应产生原因与防范措施（线程池隔离、信号量隔离与熔断器状态机）', '服务雪崩是指下游基础服务由于响应变慢或不可用，导致上游调用方大量请求线程积压阻塞，雪球越滚越大直至连锁导致全站微服务集群级联崩溃。防范三道防线：1. 资源隔离：- 线程池隔离：为每个依赖服务分配独立的专用线程池，某个服务瘫痪只耗尽自己的线程池，不影响其他业务；- 信号量隔离：使用轻量原子计数器控制并发数，无线程切换开销；2. 熔断机制：通过熔断器状态机（关闭 Closed ➔ 打开 Open ➔ 半开 Half-Open）动态监控错误率，达到阈值直接熔断进入降级逻辑（快速失败，不耗时间等待），半开状态尝试少量请求探测恢复；3. 严格设置全链路超时时间与重试上限。', '服务雪崩,雪崩效应,熔断器,线程池隔离,信号量隔离,快速失败,状态机,容错机制', '系统架构与设计模式', 1, 'it-220', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (221, '领域驱动设计（DDD）的核心概念：战略设计与战术设计是如何落地的？', 'DDD（Domain-Driven Design）是应对复杂业务软件系统的架构方法论：1. 战略设计（宏观切分）：建立统一通用语言（Ubiquitous Language），划分核心域、通用域与支撑域，通过【限界上下文（Bounded Context）】明确微服务边界与上下文映射关系（Context Map）；2. 战术设计（微观建模）：- 实体（Entity）：具有唯一业务身份标识且状态随生命周期演变的领域对象；- 值对象（Value Object）：没有独立标识，仅由属性值定义的不可变只读对象（如金额、地址）；- 聚合（Aggregate）与聚合根（Aggregate Root）：强一致性边界，外部只能通过聚合根进行访问与状态修改；- 领域服务（Domain Service）与仓储（Repository）：协调多个聚合并实现与底层存储技术的解耦。', 'DDD,领域驱动设计,限界上下文,聚合根,实体,值对象,战略设计,战术设计,领域建模', '系统架构与设计模式', 1, 'it-221', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();
INSERT INTO `cs_knowledge` (`id`, `question`, `answer`, `keywords`, `category`, `status`, `legacy_id`, `update_time`)
VALUES (222, '读写分离与 CQRS（命令查询职责分离）架构在千万级并发系统中的应用', '1. 读写分离：在数据层主库（Master）负责事务写操作，多个从库（Slave）负责处理海量只读查询，通过数据库主从复制保持同步；2. CQRS 架构（Command Query Responsibility Segregation）：在应用与模型层将写操作（Command，强一致、领域驱动校验、写入事务型 DB）与读操作（Query，按查询视图专门设计扁平反范式模型、直接读取 Redis / Elasticsearch 高性能引擎）彻底解耦分离。优势在于：彻底解放读写模型的互相牵制，读模型针对复杂多表关联、聚合统计与高并发实时查询进行极限性能优化，写模型保持极致纯粹的业务逻辑与事务安全。', '读写分离,CQRS,命令查询分离,架构设计,主从同步,Elasticsearch读模型,高并发架构', '系统架构与设计模式', 1, 'it-222', NOW())
ON DUPLICATE KEY UPDATE `question` = VALUES(`question`), `answer` = VALUES(`answer`), `keywords` = VALUES(`keywords`), `category` = VALUES(`category`), `status` = VALUES(`status`), `update_time` = NOW();