spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TJ_MYSQL_HOST:127.0.0.1}:${TJ_MYSQL_PORT:13306}/share?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: ${TJ_MYSQL_USERNAME:root}
    password: ${TJ_MYSQL_PASSWORD:TjLocalRoot@2026}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 3000
  quartz:
    job-store-type: jdbc
