# 集群名称
brokerClusterName = ZhiwenCluster
# Broker 名称
brokerName = broker-a
# 0 表示 Master
brokerId = 0
# 凌晨 4 点清理过期文件
deleteWhen = 04
# 文件保留 48 小时，保护云盘
fileReservedTime = 48
# 异步复制 Master
brokerRole = ASYNC_MASTER
# 异步刷盘，保护 ESSD 云盘 IOPS
flushDiskType = ASYNC_FLUSH
# NameServer 地址
namesrvAddr = zhiwen-rocketmq-namesrv:9876
# 自动创建 Topic
autoCreateTopicEnable = true
# 自动创建订阅组
autoCreateSubscriptionGroup = true
# Broker 对外提供服务的 Host
brokerIP1 = zhiwen-rocketmq-broker
# 监听端口
listenPort = 10911
# 自定义延时级别（第15级为15分钟超时期）
messageDelayLevel = 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 15m 20m 30m 1h 2h
