<template>
  <div class="note-management">
    <div class="page-header"><div><h2>笔记管理</h2><p>审核和维护学习者笔记，数据来自教育服务。</p></div></div>
    <div class="stat-cards"><el-card v-for="item in statCards" :key="item.label" shadow="hover" class="stat-card"><div class="stat-content"><div class="stat-icon" :style="{ background: item.color }">{{ item.value }}</div><strong>{{ item.label }}</strong></div></el-card></div>
    <el-card class="search-card" shadow="hover"><el-form :model="searchForm" inline @submit.prevent><el-form-item label="可见性"><el-select v-model="searchForm.isPublic" clearable placeholder="全部" style="width:120px"><el-option label="公开" :value="true"/><el-option label="私密" :value="false"/></el-select></el-form-item><el-form-item label="课程"><el-select v-model="searchForm.courseId" clearable placeholder="全部课程" style="width:180px"><el-option v-for="course in courses" :key="course.id" :label="course.name" :value="String(course.id)"/></el-select></el-form-item><el-form-item label="关键词"><el-input v-model="searchForm.keyword" clearable placeholder="标题或笔记内容" style="width:220px" @keyup.enter="handleSearch"/></el-form-item><el-form-item><el-button type="primary" @click="handleSearch">搜索</el-button><el-button @click="handleReset">重置</el-button></el-form-item></el-form></el-card>
    <el-card class="table-card" shadow="hover"><el-table v-loading="loading" :data="noteList" stripe><el-table-column prop="id" label="ID" width="100"/><el-table-column label="笔记信息" min-width="360"><template #default="{row}"><div class="note-content"><strong>{{ row.title || '学习笔记' }}</strong><span>{{ row.content }}</span><small>作者：{{ row.userName || '学习者' }} · 课程：{{ row.courseName || ('课程 #' + (row.courseId || '-')) }}</small></div></template></el-table-column><el-table-column label="可见性" width="100"><template #default="{row}"><el-tag :type="row.isPublic ? 'success' : 'info'">{{ row.isPublic ? '公开' : '私密' }}</el-tag></template></el-table-column><el-table-column prop="likes" label="点赞数" width="90"/><el-table-column prop="createTime" label="创建时间" width="180"/><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><el-button type="primary" link @click="handleView(row)">查看</el-button><el-button :type="row.isPublic ? 'warning' : 'success'" link @click="handleTogglePublic(row)">{{ row.isPublic ? '设为私密' : '设为公开' }}</el-button><el-button type="danger" link @click="handleDelete(row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="pagination.page" v-model:page-size="pagination.pageSize" :page-sizes="[10,20,50]" :total="pagination.total" layout="total,sizes,prev,pager,next,jumper" @size-change="handleSizeChange" @current-change="getNoteList"/></div></el-card>
    <el-dialog v-model="viewDialogVisible" title="笔记详情" width="620px"><div v-if="currentNote" class="note-detail"><div class="detail-header"><div><h3>{{ currentNote.title || '学习笔记' }}</h3><p>{{ currentNote.userName || '学习者' }} · {{ currentNote.createTime }}</p></div><el-tag :type="currentNote.isPublic ? 'success' : 'info'">{{ currentNote.isPublic ? '公开' : '私密' }}</el-tag></div><el-descriptions :column="1" border><el-descriptions-item label="课程">{{ currentNote.courseName || currentNote.courseId || '未关联' }}</el-descriptions-item><el-descriptions-item label="章节">{{ currentNote.catalogId || '未关联' }}</el-descriptions-item><el-descriptions-item label="点赞">{{ currentNote.likes }}</el-descriptions-item><el-descriptions-item label="内容"><div class="detail-content">{{ currentNote.content }}</div></el-descriptions-item></el-descriptions></div></el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getCoursesAll } from '@/api/api'
import { getNotesPage, removeNote, setNoteVisibility } from '@/api/question'

const searchForm = reactive({ isPublic: '', courseId: '', keyword: '' }); const pagination = reactive({ page: 1, pageSize: 10, total: 0 }); const courses = ref([]); const allNotes = ref([]); const noteList = ref([]); const loading = ref(false); const viewDialogVisible = ref(false); const currentNote = ref(null)
const statCards = computed(() => [{ label: '笔记总数', value: allNotes.value.length, color: 'linear-gradient(135deg,#667eea,#764ba2)' }, { label: '公开笔记', value: allNotes.value.filter(item => item.isPublic).length, color: 'linear-gradient(135deg,#43e97b,#38f9d7)' }, { label: '私密笔记', value: allNotes.value.filter(item => !item.isPublic).length, color: 'linear-gradient(135deg,#f093fb,#f5576c)' }])
function normalize(item) { return { ...item, id: String(item.id), title: item.title || '学习笔记', userName: item.userName || item.authorName || '学习者', isPublic: Number(item.visibility ?? 1) === 1, likes: Number(item.likes ?? item.likedTimes ?? 0), content: item.content || '', createTime: item.createTime || '' } }
async function loadCourses() { try { const response = await getCoursesAll({ pageNum: 1, pageSize: 200 }); const rows = response.data || response.rows || response.list || response; courses.value = Array.isArray(rows) ? rows.map(item => ({ id: item.id, name: item.name || item.title || item.courseName })) : [] } catch (error) { courses.value = [] } }
async function getNoteList() { loading.value = true; try { const response = await getNotesPage({ pageNo: 1, pageSize: 200 }); let rows = (response.rows || []).map(normalize); allNotes.value = rows; if (searchForm.isPublic !== '') rows = rows.filter(item => item.isPublic === searchForm.isPublic); if (searchForm.courseId) rows = rows.filter(item => String(item.courseId) === String(searchForm.courseId)); if (searchForm.keyword) { const keyword = searchForm.keyword.trim().toLowerCase(); rows = rows.filter(item => `${item.title}${item.content}`.toLowerCase().includes(keyword)) } pagination.total = rows.length; const start = (pagination.page - 1) * pagination.pageSize; noteList.value = rows.slice(start, start + pagination.pageSize) } catch (error) { noteList.value = []; pagination.total = 0; ElMessage.error('笔记列表加载失败') } finally { loading.value = false } }
function handleSearch() { pagination.page = 1; getNoteList() }; function handleReset() { Object.assign(searchForm, { isPublic: '', courseId: '', keyword: '' }); handleSearch() }; function handleSizeChange() { pagination.page = 1; getNoteList() }; function handleView(row) { currentNote.value = row; viewDialogVisible.value = true }
async function handleTogglePublic(row) { const next = !row.isPublic; const response = await setNoteVisibility(row.id, next); if (response.code === 200) { row.isPublic = next; const source = allNotes.value.find(item => item.id === row.id); if (source) source.isPublic = next; ElMessage.success(`笔记已设为${next ? '公开' : '私密'}`) } }
async function handleDelete(row) { try { await ElMessageBox.confirm('确定删除这条笔记吗？删除后不可恢复。', '请确认', { type: 'warning' }); const response = await removeNote(row.id); if (response.code === 200) { ElMessage.success('删除成功'); getNoteList() } } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error('删除失败') } }
onMounted(() => { loadCourses(); getNoteList() })
</script>

<style scoped>
.note-management{padding:20px}.page-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.page-header h2{margin:0;color:#303133;font-size:20px}.page-header p{margin:6px 0 0;color:#909399;font-size:13px}.stat-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:20px}.stat-card{border:0;border-radius:12px}.stat-content{display:flex;align-items:center;gap:16px}.stat-icon{display:flex;width:56px;height:56px;align-items:center;justify-content:center;border-radius:12px;color:#fff;font-size:24px;font-weight:700}.stat-content strong{color:#606266;font-size:14px}.search-card{margin-bottom:20px}.table-card :deep(.el-card__body){padding:0}.pagination{display:flex;justify-content:flex-end;padding:18px}.note-content{display:flex;flex-direction:column;gap:5px}.note-content strong{color:#303133}.note-content span{overflow:hidden;color:#606266;text-overflow:ellipsis;white-space:nowrap}.note-content small{color:#909399}.detail-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.detail-header h3{margin:0 0 6px}.detail-header p{margin:0;color:#909399}.detail-content{line-height:1.7;white-space:pre-wrap}@media(max-width:800px){.stat-cards{grid-template-columns:1fr}}
</style>
