<template>
  <div class="user-management">
    <div class="page-header"><div><h2>后台用户管理</h2><p>后台账号、业务角色和状态统一由 share-system 管理。</p></div><el-button type="primary" :icon="Plus" @click="handleAdd">新增用户</el-button></div>
    <el-card class="search-card" shadow="hover"><el-form :model="searchForm" inline @submit.prevent><el-form-item label="类型"><el-select v-model="searchForm.type" clearable placeholder="全部类型" style="width:130px"><el-option label="管理员" value="admin"/><el-option label="学员" value="student"/><el-option label="教师" value="teacher"/><el-option label="运营人员" value="employee"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="searchForm.status" clearable placeholder="全部状态" style="width:120px"><el-option label="正常" :value="1"/><el-option label="禁用" :value="0"/></el-select></el-form-item><el-form-item label="关键词"><el-input v-model="searchForm.keyword" clearable placeholder="姓名/账号/手机号" style="width:220px" @keyup.enter="handleSearch"/></el-form-item><el-form-item><el-button type="primary" @click="handleSearch">搜索</el-button><el-button @click="handleReset">重置</el-button></el-form-item></el-form></el-card>
    <el-card class="table-card" shadow="hover"><el-table v-loading="loading" :data="userList" stripe><el-table-column prop="id" label="ID" width="90"/><el-table-column prop="username" label="账号" min-width="160"/><el-table-column prop="nickname" label="姓名" min-width="120"/><el-table-column prop="phone" label="手机号" width="140"/><el-table-column prop="email" label="邮箱" min-width="190" show-overflow-tooltip/><el-table-column label="类型" width="105"><template #default="{row}"><el-tag :type="getUserTypeTag(row.type)">{{ getUserTypeText(row.type) }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-switch v-model="row.status" :active-value="1" :inactive-value="0" @change="handleStatusChange(row)"/></template></el-table-column><el-table-column prop="createTime" label="创建时间" width="180"/><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><el-button type="primary" link @click="handleEdit(row)">编辑</el-button><el-button type="primary" link @click="handleResetPwd(row)">重置密码</el-button><el-button type="danger" link @click="handleDelete(row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="pagination.page" v-model:page-size="pagination.pageSize" :page-sizes="[10,20,50]" :total="pagination.total" layout="total,sizes,prev,pager,next,jumper" @size-change="handleSizeChange" @current-change="getUserList"/></div></el-card>
    <el-dialog v-model="dialogVisible" :title="dialogTitle" width="520px" destroy-on-close><el-form ref="formRef" :model="formData" :rules="formRules" label-width="82px"><el-form-item label="账号" prop="username"><el-input v-model="formData.username" :disabled="Boolean(formData.id)"/></el-form-item><el-form-item label="姓名" prop="nickname"><el-input v-model="formData.nickname"/></el-form-item><el-form-item label="用户类型" prop="type"><el-select v-model="formData.type" style="width:100%"><el-option label="管理员" value="admin"/><el-option label="学员" value="student"/><el-option label="教师" value="teacher"/><el-option label="运营人员" value="employee"/></el-select></el-form-item><el-form-item label="手机号" prop="phone"><el-input v-model="formData.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="formData.email"/></el-form-item><el-form-item v-if="!formData.id" label="密码" prop="password"><el-input v-model="formData.password" type="password" show-password/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="submitting" @click="handleSubmit">确定</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { editUser, getUserList as getUsersApi, pwdReset, removeUser, saveUser, usersStatus } from '@/api/user'

const searchForm = reactive({ type: '', status: '', keyword: '' }); const pagination = reactive({ page: 1, pageSize: 10, total: 0 }); const userList = ref([]); const loading = ref(false); const submitting = ref(false)
const dialogVisible = ref(false); const dialogTitle = ref(''); const formRef = ref(null); const formData = reactive({ id: null, username: '', nickname: '', phone: '', email: '', type: 'student', password: '' })
const formRules = { username: [{ required: true, message: '请输入账号', trigger: 'blur' }], nickname: [{ required: true, message: '请输入姓名', trigger: 'blur' }], type: [{ required: true, message: '请选择类型', trigger: 'change' }], phone: [{ required: true, message: '请输入手机号', trigger: 'blur' }], password: [{ required: true, message: '请输入密码', trigger: 'blur' }, { min: 6, message: '密码长度不能少于6位', trigger: 'blur' }] }
function normalize(item) { return { ...item, id: String(item.id ?? item.userId ?? ''), username: item.username || item.userName || '', nickname: item.nickname || item.nickName || item.name || item.username, phone: item.phone || item.phonenumber || '', status: Number(item.enabled ?? (String(item.status) === '0' ? 1 : 0)), type: item.type || ({ '00': 'admin', '01': 'student', '02': 'teacher', '03': 'employee' }[item.userType] || 'admin') } }
async function getUserList() { loading.value = true; try { const response = await getUsersApi({ pageNum: 1, pageSize: 200 }); let rows = (response.rows || []).map(normalize); if (searchForm.type) rows = rows.filter(item => item.type === searchForm.type); if (searchForm.status !== '') rows = rows.filter(item => item.status === Number(searchForm.status)); if (searchForm.keyword) { const keyword = searchForm.keyword.trim().toLowerCase(); rows = rows.filter(item => `${item.nickname}${item.username}${item.phone}`.toLowerCase().includes(keyword)) } pagination.total = rows.length; const start = (pagination.page - 1) * pagination.pageSize; userList.value = rows.slice(start, start + pagination.pageSize) } catch (error) { userList.value = []; pagination.total = 0; ElMessage.error('用户列表加载失败') } finally { loading.value = false } }
function handleSearch() { pagination.page = 1; getUserList() }; function handleReset() { Object.assign(searchForm, { type: '', status: '', keyword: '' }); handleSearch() }; function handleSizeChange() { pagination.page = 1; getUserList() }
function handleAdd() { dialogTitle.value = '新增用户'; Object.assign(formData, { id: null, username: `user_${Date.now()}`, nickname: '', phone: '', email: '', type: 'student', password: '' }); dialogVisible.value = true }; function handleEdit(row) { dialogTitle.value = '编辑用户'; Object.assign(formData, { ...row, password: '' }); dialogVisible.value = true }
async function handleSubmit() { if (!(await formRef.value?.validate().catch(() => false))) return; submitting.value = true; try { const response = formData.id ? await editUser({ ...formData }) : await saveUser({ ...formData }); if (response.code === 200) { ElMessage.success(formData.id ? '编辑成功' : '新增成功'); dialogVisible.value = false; getUserList() } } finally { submitting.value = false } }
async function handleDelete(row) { try { await ElMessageBox.confirm(`确定删除用户“${row.nickname}”吗？`, '请确认', { type: 'warning' }); const response = await removeUser(row.id); if (response.code === 200) { ElMessage.success('删除成功'); getUserList() } } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error('删除失败') } }
async function handleStatusChange(row) { const response = await usersStatus({ id: row.id, status: row.status }); if (response.code !== 200) { row.status = row.status ? 0 : 1; ElMessage.error('状态更新失败') } }
async function handleResetPwd(row) { try { await ElMessageBox.confirm(`确定重置“${row.nickname}”的密码吗？重置后密码为 123456。`, '请确认', { type: 'warning' }); const response = await pwdReset(row.id); if (response.code === 200) ElMessage.success('密码已重置为 123456') } catch (error) { if (error !== 'cancel' && error !== 'close') ElMessage.error('密码重置失败') } }
function getUserTypeTag(type) { return ({ admin: 'danger', teacher: 'success', employee: 'warning', student: '' }[type] || 'info') }; function getUserTypeText(type) { return ({ admin: '管理员', teacher: '教师', employee: '运营人员', student: '学员' }[type] || '未知') }
onMounted(getUserList)
</script>

<style scoped>
.user-management{padding:20px}.page-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.page-header h2{margin:0;color:#303133;font-size:20px}.page-header p{margin:6px 0 0;color:#909399;font-size:13px}.search-card{margin-bottom:20px}.table-card :deep(.el-card__body){padding:0}.pagination{display:flex;justify-content:flex-end;padding:18px}@media(max-width:800px){.page-header{align-items:flex-start;gap:12px;flex-direction:column}}
</style>
