# 认证服务本地配置兜底
qq:
  mail:
    host: ${QQ_MAIL_HOST:smtp.qq.com}
    port: ${QQ_MAIL_PORT:465}
    username: ${QQ_MAIL_USERNAME:a2416363666@qq.com}
    password: ${QQ_MAIL_PASSWORD:favpmuxwrwfbebbh}
    sender: ${QQ_MAIL_SENDER:a2416363666@qq.com}
